<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Chapter 3: Forest Composition &amp; Structure | _main.knit</title>
  <meta name="description" content="This short book should help you to get a better understanding of how the forest attributes analysis works, what you might want to consider in order to perform that are applicable for their respective purpose." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Chapter 3: Forest Composition &amp; Structure | _main.knit" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://doi.org/10.5281/zenodo.22606690/fig/MPG_Logo_green.png" />
  <meta property="og:description" content="This short book should help you to get a better understanding of how the forest attributes analysis works, what you might want to consider in order to perform that are applicable for their respective purpose." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Chapter 3: Forest Composition &amp; Structure | _main.knit" />
  
  <meta name="twitter:description" content="This short book should help you to get a better understanding of how the forest attributes analysis works, what you might want to consider in order to perform that are applicable for their respective purpose." />
  <meta name="twitter:image" content="https://doi.org/10.5281/zenodo.22606690/fig/MPG_Logo_green.png" />

<meta name="author" content="J. David Urquiza-Munoz" />


<meta name="date" content="2026-09-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chapter-2-forest-stand-structure.html"/>
<link rel="next" href="chapter-4-allometric-relationships-and-statistical-correlation.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/rglWebGL-binding-1.3.36/rglWebGL.js"></script>
<link href="libs/rglwidgetClass-1.3.36/rgl.css" rel="stylesheet" />
<script src="libs/rglwidgetClass-1.3.36/rglClass.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/utils.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/buffer.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/subscenes.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/shaders.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/shadersrc.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/textures.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/projection.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/mouse.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/init.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/pieces.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/draw.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/controls.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/selection.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/rglTimer.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/pretty.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/axes.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/animation.src.js"></script>
<script src="libs/CanvasMatrix4-1.3.36/CanvasMatrix.src.js"></script>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FMG5FF37YL"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FMG5FF37YL');
</script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-this-book"><i class="fa fa-check"></i>About this book</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-cite-this-book"><i class="fa fa-check"></i>How to Cite this Book</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the author</a>
<ul>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html#j.-david-urquiza-mu%C3%B1oz"><i class="fa fa-check"></i>J. David Urquiza Muñoz</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html"><i class="fa fa-check"></i><b>1</b> Chapter 1: Introduction to Forest Data in R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#download-project-files"><i class="fa fa-check"></i><b>1.1</b> Download Project Files</a></li>
<li class="chapter" data-level="1.2" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#setting-your-working-directory"><i class="fa fa-check"></i><b>1.2</b> Setting Your Working Directory</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#using-rstudio-projects"><i class="fa fa-check"></i><b>1.2.1</b> Using RStudio Projects</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#setting-up-the-environment"><i class="fa fa-check"></i><b>1.3</b> Setting up the Environment</a></li>
<li class="chapter" data-level="1.4" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#importing-the-inventory-data"><i class="fa fa-check"></i><b>1.4</b> Importing the Inventory Data</a></li>
<li class="chapter" data-level="1.5" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#data-cleaning-and-standardization"><i class="fa fa-check"></i><b>1.5</b> Data Cleaning and Standardization</a></li>
<li class="chapter" data-level="1.6" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#exploring-the-cleaned-data"><i class="fa fa-check"></i><b>1.6</b> Exploring the Cleaned Data</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html"><i class="fa fa-check"></i><b>2</b> Chapter 2: Forest Stand Structure</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#diameter-at-breast-height-dbh"><i class="fa fa-check"></i><b>2.1</b> Diameter at Breast Height (DBH)</a></li>
<li class="chapter" data-level="2.2" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#stand-level-metrics-density-and-basal-area-per-hectare"><i class="fa fa-check"></i><b>2.2</b> Stand-Level Metrics: Density and Basal Area (Per Hectare)</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#quantitative-stand-metrics"><i class="fa fa-check"></i><b>2.2.1</b> Quantitative Stand Metrics</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#structural-composition-dbh-by-dominant-species"><i class="fa fa-check"></i><b>2.3</b> Structural Composition: DBH by Dominant Species</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#structural-roles-of-dominant-species"><i class="fa fa-check"></i><b>2.3.1</b> Structural Roles of Dominant Species</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#d-spatial-distribution-and-mapping"><i class="fa fa-check"></i><b>2.4</b> 2D Spatial Distribution and Mapping</a></li>
<li class="chapter" data-level="2.5" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#creating-spatial-data"><i class="fa fa-check"></i><b>2.5</b> Creating Spatial Data</a></li>
<li class="chapter" data-level="2.6" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#advanced-spatial-structure-point-pattern-analysis-by-species"><i class="fa fa-check"></i><b>2.6</b> Advanced Spatial Structure: Point Pattern Analysis by Species</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#mapping-forest-structure"><i class="fa fa-check"></i><b>2.6.1</b> Mapping Forest Structure</a></li>
<li class="chapter" data-level="2.6.2" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#visualizing-species-distribution"><i class="fa fa-check"></i><b>2.6.2</b> Visualizing Species Distribution</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#analyzing-spatial-clustering-with-the-morisita-index"><i class="fa fa-check"></i><b>2.7</b> Analyzing Spatial Clustering with the Morisita Index</a></li>
<li class="chapter" data-level="2.8" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#spatial-visualization-of-dbh-and-tree-height"><i class="fa fa-check"></i><b>2.8</b> Spatial Visualization of DBH and tree height</a></li>
<li class="chapter" data-level="2.9" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#biomass-and-carbon-as-structural-attributes"><i class="fa fa-check"></i><b>2.9</b> Biomass and carbon as structural attributes</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#extracting-wood-density-and-calculating-agb"><i class="fa fa-check"></i><b>2.9.1</b> Extracting Wood Density and Calculating AGB</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="chapter-2-forest-stand-structure.html"><a href="chapter-2-forest-stand-structure.html#spatial-distribution-of-carbon"><i class="fa fa-check"></i><b>2.10</b> Spatial distribution of carbon</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter-3-forest-composition-structure.html"><a href="chapter-3-forest-composition-structure.html"><i class="fa fa-check"></i><b>3</b> Chapter 3: Forest Composition &amp; Structure</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chapter-3-forest-composition-structure.html"><a href="chapter-3-forest-composition-structure.html#species-composition"><i class="fa fa-check"></i><b>3.1</b> Species Composition</a></li>
<li class="chapter" data-level="3.2" data-path="chapter-3-forest-composition-structure.html"><a href="chapter-3-forest-composition-structure.html#quantifying-biodiversity-diversity-indices"><i class="fa fa-check"></i><b>3.2</b> Quantifying biodiversity: diversity indices</a></li>
<li class="chapter" data-level="3.3" data-path="chapter-3-forest-composition-structure.html"><a href="chapter-3-forest-composition-structure.html#species-accumulation-curves"><i class="fa fa-check"></i><b>3.3</b> Species accumulation curves</a></li>
<li class="chapter" data-level="3.4" data-path="chapter-3-forest-composition-structure.html"><a href="chapter-3-forest-composition-structure.html#synthesis-of-structure-and-composition-the-importance-value-index-ivi"><i class="fa fa-check"></i><b>3.4</b> Synthesis of Structure and Composition: The Importance Value Index (IVI)</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapter-4-allometric-relationships-and-statistical-correlation.html"><a href="chapter-4-allometric-relationships-and-statistical-correlation.html"><i class="fa fa-check"></i><b>4</b> Chapter 4: Allometric Relationships and Statistical Correlation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chapter-4-allometric-relationships-and-statistical-correlation.html"><a href="chapter-4-allometric-relationships-and-statistical-correlation.html#allometric-relationships-and-statistical-correlation"><i class="fa fa-check"></i><b>4.1</b> Allometric Relationships and Statistical Correlation</a></li>
<li class="chapter" data-level="4.2" data-path="chapter-4-allometric-relationships-and-statistical-correlation.html"><a href="chapter-4-allometric-relationships-and-statistical-correlation.html#mathematical-models"><i class="fa fa-check"></i><b>4.2</b> Mathematical Models</a></li>
<li class="chapter" data-level="4.3" data-path="chapter-4-allometric-relationships-and-statistical-correlation.html"><a href="chapter-4-allometric-relationships-and-statistical-correlation.html#visualizing-the-correlation"><i class="fa fa-check"></i><b>4.3</b> Visualizing the Correlation</a></li>
<li class="chapter" data-level="4.4" data-path="chapter-4-allometric-relationships-and-statistical-correlation.html"><a href="chapter-4-allometric-relationships-and-statistical-correlation.html#estimating-missing-heights"><i class="fa fa-check"></i><b>4.4</b> Estimating Missing Heights</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><i class="fa fa-check"></i><b>5</b> Chapter 5: Canopy Gap Dynamics using 3D LiDAR</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#point-cloud-import-and-preprocessing"><i class="fa fa-check"></i><b>5.1</b> Point cloud import and preprocessing</a></li>
<li class="chapter" data-level="5.2" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#point-cloud-normalization"><i class="fa fa-check"></i><b>5.2</b> Point Cloud Normalization</a></li>
<li class="chapter" data-level="5.3" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#d-visualization"><i class="fa fa-check"></i><b>5.3</b> 3D visualization</a></li>
<li class="chapter" data-level="5.4" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#canopy-height-model-chm-generation"><i class="fa fa-check"></i><b>5.4</b> Canopy Height Model (CHM) Generation</a></li>
<li class="chapter" data-level="5.5" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#canopy-gap-detection-and-delineation"><i class="fa fa-check"></i><b>5.5</b> Canopy Gap Detection and Delineation</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#vertical-point-density-profile"><i class="fa fa-check"></i><b>5.5.1</b> Vertical Point Density Profile</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>6</b> References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><p><img src="fig/ForestAR_logo.jpg" style="width:8in" /></p>
<p>Forest Attributes Analysis in R - ForestAR</p></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="google_translate_element" style="padding: 10px; text-align: right;"></div>
<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({
    pageLanguage: 'en', 
    includedLanguages: 'es,pt',
    layout: google.translate.TranslateElement.InlineLayout.SIMPLE
  }, 'google_translate_element');
}
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

<div style="padding: 10px; text-align: center; font-size: 0.85em; border-top: 1px solid rgba(0,0,0,0.1); margin-top: 10px;">
  <strong>Connect:</strong><br>
  <a href="https://www.researchgate.net/profile/J-David-Urquiza-Munoz?ev=hdr_xprf" target="_blank" style="margin: 0 3px;">ResearchGate</a> | 
  <a href="https://www.linkedin.com/in/j-david-urquiza-munoz-446bb223/" target="_blank" style="margin: 0 3px;">LinkedIn</a> | 
  <a href="https://x.com/JoDaUrMu1" target="_blank" style="margin: 0 3px;">X</a>
</div>
<div id="chapter-3-forest-composition-structure" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Chapter 3: Forest Composition &amp; Structure<a href="chapter-3-forest-composition-structure.html#chapter-3-forest-composition-structure" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>With our inventory data cleaned and standardized, we can now explore the ecological characteristics of our forest stand. Two of the most fundamental questions in any forest inventory are: What species are growing here? and How big are they?</p>
<p>In this chapter, we will use the ggplot2 package (which is loaded automatically with tidyverse) to create clear, publication-ready visualizations of our forest’s composition and structure.</p>
<div id="species-composition" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Species Composition<a href="chapter-3-forest-composition-structure.html#species-composition" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Tropical and Neotropical forests are incredibly diverse. Visualizing the abundance of every single species in a single chart can result in a cluttered and unreadable mess. Instead, a standard practice is to isolate and visualize the most dominant species to understand the primary makeup of the canopy.</p>
<p>Let’s calculate the top 10 most abundant species in our dataset and create a horizontal bar chart.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="chapter-3-forest-composition-structure.html#cb33-1" tabindex="-1"></a><span class="co"># Calculate species frequencies and filter for the top 10</span></span>
<span id="cb33-2"><a href="chapter-3-forest-composition-structure.html#cb33-2" tabindex="-1"></a>top_species <span class="ot">&lt;-</span> inventory_clean <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="chapter-3-forest-composition-structure.html#cb33-3" tabindex="-1"></a>  <span class="fu">count</span>(Scientific_Name, <span class="at">name =</span> <span class="st">&quot;Count&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="chapter-3-forest-composition-structure.html#cb33-4" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Count)) <span class="sc">%&gt;%</span></span>
<span id="cb33-5"><a href="chapter-3-forest-composition-structure.html#cb33-5" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> Count, <span class="at">n =</span> <span class="dv">10</span>)</span>
<span id="cb33-6"><a href="chapter-3-forest-composition-structure.html#cb33-6" tabindex="-1"></a></span>
<span id="cb33-7"><a href="chapter-3-forest-composition-structure.html#cb33-7" tabindex="-1"></a><span class="co"># Create a horizontal bar chart</span></span>
<span id="cb33-8"><a href="chapter-3-forest-composition-structure.html#cb33-8" tabindex="-1"></a><span class="fu">ggplot</span>(top_species, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Scientific_Name, Count), <span class="at">y =</span> Count)) <span class="sc">+</span></span>
<span id="cb33-9"><a href="chapter-3-forest-composition-structure.html#cb33-9" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;steelblue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb33-10"><a href="chapter-3-forest-composition-structure.html#cb33-10" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> <span class="co"># Flips the axes for easier reading of species names</span></span>
<span id="cb33-11"><a href="chapter-3-forest-composition-structure.html#cb33-11" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb33-12"><a href="chapter-3-forest-composition-structure.html#cb33-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Dominant Species in the Forest Stand&quot;</span>,</span>
<span id="cb33-13"><a href="chapter-3-forest-composition-structure.html#cb33-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Scientific Name&quot;</span>,</span>
<span id="cb33-14"><a href="chapter-3-forest-composition-structure.html#cb33-14" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Number of Individuals&quot;</span></span>
<span id="cb33-15"><a href="chapter-3-forest-composition-structure.html#cb33-15" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb33-16"><a href="chapter-3-forest-composition-structure.html#cb33-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb33-17"><a href="chapter-3-forest-composition-structure.html#cb33-17" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb33-18"><a href="chapter-3-forest-composition-structure.html#cb33-18" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;italic&quot;</span>) <span class="co"># Standard practice: italicize scientific names</span></span>
<span id="cb33-19"><a href="chapter-3-forest-composition-structure.html#cb33-19" tabindex="-1"></a>  )</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:species-composition"></span>
<img src="_main_files/figure-html/species-composition-1.png" alt="Top 10 most abundant tree species in the inventory." width="672" />
<p class="caption">
Figure 3.1: Top 10 most abundant tree species in the inventory.
</p>
</div>
<p><strong>Interpretation of species dominance</strong></p>
<p><strong><em>Plot observations: </em></strong>
The horizontal bar chart visualizes the ten most abundant tree species within the sampled forest stand, ranked by the number of individuals. Pouteria guianensis emerges as the clear dominant species with approximately 35 individuals, followed closely by Protium amazonicum (30 individuals) and Virola duckei (29 individuals). The gradual decline in stem counts among the top tier—transitioning down to species like Eschweilera albiflora and the understory palm Astrocaryum murumuru—illustrates a heavily skewed abundance distribution where a small handful of species constitute a significant structural proportion of the stand.</p>
<p><strong><em>Ecological theory and context: </em></strong>
This pattern of structural dominance is a foundational concept in tropical forest ecology. While lowland Amazonian forests are globally renowned for their immense alpha diversity, they are rarely egalitarian. The plot perfectly reflects the Hyperdominance Theory, which posits that despite the Amazon basin harboring an estimated 16,000 tree species, a remarkably small fraction—roughly 227 species (1.4%)—accounts for exactly half of all individual stems across the biome.<span class="citation"><a href="#fn20" class="footnote-ref" id="fnref20"><sup>20</sup></a></span></p>
<p>Several of the taxa identified in this plot are classic hallmarks of this phenomenon. Genera such as Eschweilera, Protium, and Astrocaryum are frequently documented as hyperdominant oligarchs in terra firme and restinga ecosystems across the western and northwestern Amazon.</p>
<p>This skewed rank-abundance distribution can be explained by two primary ecological mechanisms:</p>
<ul>
<li><p>Oligarchic forest structure: As described by Pitman et al. (2001)<span class="citation">,<a href="#fn21" class="footnote-ref" id="fnref21"><sup>21</sup></a></span> certain highly competitive, shade-tolerant species form widespread “oligarchies.” These species possess functional traits that allow them to successfully recruit, survive, and dominate across a broad range of environmental gradients and gap-phase dynamics, effectively out-competing rarer specialists.</p></li>
<li><p>Environmental filtering: The high abundance of specific dominant taxa often reflects local adaptation to specific edaphic (soil) conditions or hydrological regimes. Visualizing this dominance is a critical first step in forest attribute analysis, as these highly abundant species disproportionately drive ecosystem functioning, aboveground biomass accumulation, and regional biogeochemical cycling.</p></li>
</ul>
</div>
<div id="quantifying-biodiversity-diversity-indices" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Quantifying biodiversity: diversity indices<a href="chapter-3-forest-composition-structure.html#quantifying-biodiversity-diversity-indices" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>While our bar chart shows the most common species, it does not tell us the overall diversity of the stand. To quantify this, ecologists rely on diversity indices. The two most common are the Shannon-Wiener Index (<span class="math inline">\(H&#39;\)</span>) and the Simpson Index (<span class="math inline">\(D\)</span>).</p>
<p>Shannon-Wiener Index (<span class="math inline">\(H&#39;\)</span>): Accounts for both abundance and evenness of the species present.<span class="citation"><a href="#fn22" class="footnote-ref" id="fnref22"><sup>22</sup></a></span> A higher value indicates higher diversity.The formula is:</p>
<p><span class="math display">\[H&#39; = -\sum_{i=1}^{S} p_i \ln(p_i)\]</span>
where <span class="math inline">\(p_i\)</span> is the proportion of individuals belonging to the <span class="math inline">\(i\)</span>th species.</p>
<p>Simpson Index (<span class="math inline">\(D\)</span>):<span class="citation"><a href="#fn23" class="footnote-ref" id="fnref23"><sup>23</sup></a></span> Measures the probability that two individuals randomly selected from a sample will belong to the same species.Let’s use the vegan package to calculate these metrics for our plot.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="chapter-3-forest-composition-structure.html#cb34-1" tabindex="-1"></a><span class="co"># Install vegan if needed: install.packages(&quot;vegan&quot;)</span></span>
<span id="cb34-2"><a href="chapter-3-forest-composition-structure.html#cb34-2" tabindex="-1"></a><span class="fu">library</span>(vegan)</span></code></pre></div>
<pre><code>## Warning: package &#39;vegan&#39; was built under R version 4.4.3</code></pre>
<pre><code>## Warning: package &#39;permute&#39; was built under R version 4.4.3</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="chapter-3-forest-composition-structure.html#cb37-1" tabindex="-1"></a><span class="co"># First, we need a table of species counts (a community matrix)</span></span>
<span id="cb37-2"><a href="chapter-3-forest-composition-structure.html#cb37-2" tabindex="-1"></a>species_counts <span class="ot">&lt;-</span> inventory_clean <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="chapter-3-forest-composition-structure.html#cb37-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Scientific_Name =</span> <span class="fu">ifelse</span>(Scientific_Name <span class="sc">==</span> <span class="st">&quot;&quot;</span>, <span class="st">&quot;Unknown&quot;</span>, Scientific_Name)) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="chapter-3-forest-composition-structure.html#cb37-4" tabindex="-1"></a>  <span class="fu">count</span>(Scientific_Name) <span class="sc">%&gt;%</span></span>
<span id="cb37-5"><a href="chapter-3-forest-composition-structure.html#cb37-5" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Scientific_Name, <span class="at">values_from =</span> n, <span class="at">values_fill =</span> <span class="dv">0</span>)</span>
<span id="cb37-6"><a href="chapter-3-forest-composition-structure.html#cb37-6" tabindex="-1"></a></span>
<span id="cb37-7"><a href="chapter-3-forest-composition-structure.html#cb37-7" tabindex="-1"></a><span class="co"># Calculate Shannon Index</span></span>
<span id="cb37-8"><a href="chapter-3-forest-composition-structure.html#cb37-8" tabindex="-1"></a>shannon_index <span class="ot">&lt;-</span> <span class="fu">diversity</span>(species_counts, <span class="at">index =</span> <span class="st">&quot;shannon&quot;</span>)</span>
<span id="cb37-9"><a href="chapter-3-forest-composition-structure.html#cb37-9" tabindex="-1"></a></span>
<span id="cb37-10"><a href="chapter-3-forest-composition-structure.html#cb37-10" tabindex="-1"></a><span class="co"># Calculate Simpson Index</span></span>
<span id="cb37-11"><a href="chapter-3-forest-composition-structure.html#cb37-11" tabindex="-1"></a>simpson_index <span class="ot">&lt;-</span> <span class="fu">diversity</span>(species_counts, <span class="at">index =</span> <span class="st">&quot;simpson&quot;</span>)</span>
<span id="cb37-12"><a href="chapter-3-forest-composition-structure.html#cb37-12" tabindex="-1"></a></span>
<span id="cb37-13"><a href="chapter-3-forest-composition-structure.html#cb37-13" tabindex="-1"></a><span class="co"># Calculate Species Richness (Total number of unique species)</span></span>
<span id="cb37-14"><a href="chapter-3-forest-composition-structure.html#cb37-14" tabindex="-1"></a>richness <span class="ot">&lt;-</span> <span class="fu">specnumber</span>(species_counts)</span>
<span id="cb37-15"><a href="chapter-3-forest-composition-structure.html#cb37-15" tabindex="-1"></a></span>
<span id="cb37-16"><a href="chapter-3-forest-composition-structure.html#cb37-16" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb37-17"><a href="chapter-3-forest-composition-structure.html#cb37-17" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Species Richness (S):&quot;</span>, richness, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Species Richness (S): 207</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="chapter-3-forest-composition-structure.html#cb39-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Shannon Index (H&#39;):&quot;</span>, <span class="fu">round</span>(shannon_index, <span class="dv">3</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Shannon Index (H&#39;): 4.639</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="chapter-3-forest-composition-structure.html#cb41-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Simpson Index (D):&quot;</span>, <span class="fu">round</span>(simpson_index, <span class="dv">3</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Simpson Index (D): 0.982</code></pre>
<p><strong>Interpretation of Alpha diversity metrics</strong></p>
<p>The calculated alpha diversity metrics reveal an exceptionally complex and species-rich forest stand. A Species Richness (S) of 207 indicates a vast array of distinct taxa coexisting within the sampled area. The Shannon-Wiener Index (H’) of 4.639 is notably high; while typical ecological communities generally yield values between 1.5 and 3.5,<span class="citation"><a href="#fn24" class="footnote-ref" id="fnref24"><sup>24</sup></a></span> scores exceeding 4.0 are almost exclusively the hallmark of highly intact tropical rainforests.<span class="citation"><a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a></span> Finally, the Simpson Index score of 0.982 (interpreted here as Simpson’s Diversity Index, <span class="math inline">\(1 - D\)</span>) suggests that if two individual trees were randomly sampled from this stand, there is a 98.2% probability that they would belong to entirely different species.</p>
<p><strong><em>Ecological theory and context</em></strong></p>
<p>These metrics highlight a fascinating structural dichotomy typical of the Amazon basin. While the previous visualization demonstrated that a handful of species dominate the overall stem count (hyperdominance), the extremely high Shannon Index and Species Richness underscore the ecological importance of the “long tail” of rare species.</p>
<p>This extreme diversity is maintained by several interacting ecological mechanisms:</p>
<ul>
<li><p>The Janzen-Connell Hypothesis: This foundational theory explains how such high richness (S = 207) can be sustained without competitive exclusion. It posits that host-specific natural enemies (such as specialized herbivores and fungal pathogens) disproportionately attack the seeds and seedlings of highly abundant species near the parent tree.<span class="citation"><a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a></span> This density-dependent mortality prevents any single species from entirely monopolizing the stand, actively maintaining space for hundreds of rarer species to recruit and persist.</p></li>
<li><p>Niche partitioning and gap dynamics: The high Shannon Index (H’) reflects not just raw species count, but a relatively equitable distribution of those rare taxa across the available microhabitats. Small-scale disturbances, such as the localized canopy gaps caused by windthrow or natural tree falls, create shifting mosaics of light availability that allow different functional groups to coexist.</p></li>
<li><p>Metric sensitivity: It is important to note the mathematical weighting of these indices for forest attributes analysis. The Shannon Index (<span class="math inline">\(H&#39;\)</span>) is highly sensitive to the presence of rare species (the long tail), whereas the Simpson Index is weighted more heavily toward the evenness of the most common species.<span class="citation"><a href="#fn27" class="footnote-ref" id="fnref27"><sup>27</sup></a></span> The fact that both indices are exceptionally high confirms a stable, highly diverse ecosystem structure.</p></li>
</ul>
</div>
<div id="species-accumulation-curves" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Species accumulation curves<a href="chapter-3-forest-composition-structure.html#species-accumulation-curves" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In dense tropical canopies, a critical question is: Did we sample a large enough area to capture the true diversity of the forest?</p>
<p>A Species Accumulation Curve plots the number of new species discovered as the sampling effort (number of trees or plots) increases. If the curve flattens out (reaches an asymptote), our sampling effort was sufficient. If it is still climbing steeply, many rare species remain undiscovered.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="chapter-3-forest-composition-structure.html#cb43-1" tabindex="-1"></a>presence_matrix <span class="ot">&lt;-</span> inventory_clean <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="chapter-3-forest-composition-structure.html#cb43-2" tabindex="-1"></a>  <span class="co"># 1. Add this filter to remove empty strings first!</span></span>
<span id="cb43-3"><a href="chapter-3-forest-composition-structure.html#cb43-3" tabindex="-1"></a>  <span class="fu">filter</span>(Scientific_Name <span class="sc">!=</span> <span class="st">&quot;&quot;</span>, <span class="sc">!</span><span class="fu">is.na</span>(Scientific_Name)) <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="chapter-3-forest-composition-structure.html#cb43-4" tabindex="-1"></a>  <span class="co"># 2. Proceed with the rest of the code</span></span>
<span id="cb43-5"><a href="chapter-3-forest-composition-structure.html#cb43-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Presence =</span> <span class="dv">1</span>, <span class="at">Tree_Index =</span> <span class="fu">row_number</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb43-6"><a href="chapter-3-forest-composition-structure.html#cb43-6" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Scientific_Name, <span class="at">values_from =</span> Presence, <span class="at">values_fill =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-7"><a href="chapter-3-forest-composition-structure.html#cb43-7" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Plot_ID, <span class="sc">-</span>Tree_ID, <span class="sc">-</span>Common_Name, <span class="sc">-</span>DBH_cm, <span class="sc">-</span>Easting, <span class="sc">-</span>Northing, <span class="sc">-</span>Tree_Index)</span>
<span id="cb43-8"><a href="chapter-3-forest-composition-structure.html#cb43-8" tabindex="-1"></a></span>
<span id="cb43-9"><a href="chapter-3-forest-composition-structure.html#cb43-9" tabindex="-1"></a>accum_curve <span class="ot">&lt;-</span> <span class="fu">specaccum</span>(presence_matrix, <span class="at">method =</span> <span class="st">&quot;exact&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in cor(x &gt; 0): the standard deviation is zero</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="chapter-3-forest-composition-structure.html#cb45-1" tabindex="-1"></a><span class="fu">plot</span>(accum_curve, <span class="at">ci.type =</span> <span class="st">&quot;poly&quot;</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">ci.lty =</span> <span class="dv">0</span>, <span class="at">ci.col =</span> <span class="st">&quot;lightblue&quot;</span>,</span>
<span id="cb45-2"><a href="chapter-3-forest-composition-structure.html#cb45-2" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Number of Trees Sampled&quot;</span>,</span>
<span id="cb45-3"><a href="chapter-3-forest-composition-structure.html#cb45-3" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Cumulative Number of Species&quot;</span>,</span>
<span id="cb45-4"><a href="chapter-3-forest-composition-structure.html#cb45-4" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Species Accumulation Curve&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:species-accumulation"></span>
<img src="_main_files/figure-html/species-accumulation-1.png" alt="Species accumulation curve showing the rate at which new species are encountered as sampling effort increases." width="672" />
<p class="caption">
Figure 3.2: Species accumulation curve showing the rate at which new species are encountered as sampling effort increases.
</p>
</div>
<p><strong>Interpretation of the species accumulation curve</strong></p>
<p>The Species Accumulation Curve (SAC) visualizes the rate at which new species are discovered as the sampling effort increases (measured here by the cumulative number of individual trees sampled). The solid blue line represents the expected species richness, flanked by a shaded 95% confidence interval ribbon. Notably, after sampling nearly 700 individual stems, the cumulative species count exceeds 200, yet the curve remains strictly ascending. It shows no clear sign of reaching a plateau or asymptote.</p>
<p><strong><em>Ecological theory and context</em></strong></p>
<p>In forest attribute analysis, the SAC serves as a critical diagnostic tool for evaluating sampling completeness. An asymptotic curve (one that flattens out) would suggest that the community has been exhaustively surveyed and that further sampling would yield few, if any, new species.</p>
<p>However, the continuous upward trajectory observed in this plot is precisely what ecologists expect when surveying highly intact, hyper-diverse tropical ecosystems, such as those found across the northwestern Amazon.<span class="citation"><a href="#fn28" class="footnote-ref" id="fnref28"><sup>28</sup></a></span> This pattern reinforces the diversity metrics calculated previously and is driven by the following factors:</p>
<ul>
<li><p>The rare species tail: As established by the high Shannon and Simpson indices, tropical forests contain a massive proportion of extremely rare taxa. In standard field plots, many of these species occur as “singletons” (represented by only one individual) or “doubletons.” Because this pool of rare species is so vast, every new sampling transect or plot continues to slowly add unique taxa to the overall inventory, preventing the curve from flattening.<span class="citation"><a href="#fn29" class="footnote-ref" id="fnref29"><sup>29</sup></a></span></p></li>
<li><p>Estimating true richness: Because the empirical count (207 species) has not reached an asymptote, we can conclude that the observed richness is an underestimate of the true community richness. In these scenarios, researchers typically apply non-parametric asymptotic estimators (such as Chao1, abundance-based coverage estimator (ACE), or Jackknife methods) to mathematically extrapolate where the curve would eventually stabilize if the entire forest were sampled.<span class="citation"><a href="#fn30" class="footnote-ref" id="fnref30"><sup>30</sup></a></span></p></li>
</ul>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="chapter-3-forest-composition-structure.html#cb46-1" tabindex="-1"></a><span class="fu">library</span>(vegan)</span>
<span id="cb46-2"><a href="chapter-3-forest-composition-structure.html#cb46-2" tabindex="-1"></a><span class="fu">library</span>(tibble) <span class="co"># Needed to convert the Plot_ID column into row names</span></span>
<span id="cb46-3"><a href="chapter-3-forest-composition-structure.html#cb46-3" tabindex="-1"></a></span>
<span id="cb46-4"><a href="chapter-3-forest-composition-structure.html#cb46-4" tabindex="-1"></a><span class="co"># 1. Create a community matrix grouped by Subplot (Plot_ID)</span></span>
<span id="cb46-5"><a href="chapter-3-forest-composition-structure.html#cb46-5" tabindex="-1"></a>subplot_matrix <span class="ot">&lt;-</span> inventory_clean <span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="chapter-3-forest-composition-structure.html#cb46-6" tabindex="-1"></a>  <span class="co"># Ensure we have no blank species names</span></span>
<span id="cb46-7"><a href="chapter-3-forest-composition-structure.html#cb46-7" tabindex="-1"></a>  <span class="fu">filter</span>(Scientific_Name <span class="sc">!=</span> <span class="st">&quot;&quot;</span>, <span class="sc">!</span><span class="fu">is.na</span>(Scientific_Name)) <span class="sc">%&gt;%</span></span>
<span id="cb46-8"><a href="chapter-3-forest-composition-structure.html#cb46-8" tabindex="-1"></a>  <span class="co"># Count the number of each species PER subplot</span></span>
<span id="cb46-9"><a href="chapter-3-forest-composition-structure.html#cb46-9" tabindex="-1"></a>  <span class="fu">count</span>(Plot_ID, Scientific_Name) <span class="sc">%&gt;%</span></span>
<span id="cb46-10"><a href="chapter-3-forest-composition-structure.html#cb46-10" tabindex="-1"></a>  <span class="co"># Pivot into a wide matrix (Rows = Plot_ID, Columns = Species)</span></span>
<span id="cb46-11"><a href="chapter-3-forest-composition-structure.html#cb46-11" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Scientific_Name, <span class="at">values_from =</span> n, <span class="at">values_fill =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-12"><a href="chapter-3-forest-composition-structure.html#cb46-12" tabindex="-1"></a>  <span class="co"># &#39;vegan&#39; requires the matrix to be purely numeric, so we move Plot_ID to the row names</span></span>
<span id="cb46-13"><a href="chapter-3-forest-composition-structure.html#cb46-13" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="at">var =</span> <span class="st">&quot;Plot_ID&quot;</span>)</span>
<span id="cb46-14"><a href="chapter-3-forest-composition-structure.html#cb46-14" tabindex="-1"></a></span>
<span id="cb46-15"><a href="chapter-3-forest-composition-structure.html#cb46-15" tabindex="-1"></a><span class="co"># 2. Calculate the accumulation curve using the subplots</span></span>
<span id="cb46-16"><a href="chapter-3-forest-composition-structure.html#cb46-16" tabindex="-1"></a>accum_curve_subplot <span class="ot">&lt;-</span> <span class="fu">specaccum</span>(subplot_matrix, <span class="at">method =</span> <span class="st">&quot;exact&quot;</span>)</span>
<span id="cb46-17"><a href="chapter-3-forest-composition-structure.html#cb46-17" tabindex="-1"></a></span>
<span id="cb46-18"><a href="chapter-3-forest-composition-structure.html#cb46-18" tabindex="-1"></a><span class="co"># 3. Plot the results</span></span>
<span id="cb46-19"><a href="chapter-3-forest-composition-structure.html#cb46-19" tabindex="-1"></a><span class="fu">plot</span>(accum_curve_subplot, </span>
<span id="cb46-20"><a href="chapter-3-forest-composition-structure.html#cb46-20" tabindex="-1"></a>     <span class="at">ci.type =</span> <span class="st">&quot;poly&quot;</span>, <span class="at">col =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">ci.lty =</span> <span class="dv">0</span>, <span class="at">ci.col =</span> <span class="st">&quot;lightgreen&quot;</span>,</span>
<span id="cb46-21"><a href="chapter-3-forest-composition-structure.html#cb46-21" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Number of Subplots Sampled&quot;</span>,</span>
<span id="cb46-22"><a href="chapter-3-forest-composition-structure.html#cb46-22" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Cumulative Number of Species&quot;</span>,</span>
<span id="cb46-23"><a href="chapter-3-forest-composition-structure.html#cb46-23" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Species Accumulation Rate by Subplot&quot;</span>)</span>
<span id="cb46-24"><a href="chapter-3-forest-composition-structure.html#cb46-24" tabindex="-1"></a></span>
<span id="cb46-25"><a href="chapter-3-forest-composition-structure.html#cb46-25" tabindex="-1"></a><span class="co"># Add a grid for easier reading of the asymptote </span></span>
<span id="cb46-26"><a href="chapter-3-forest-composition-structure.html#cb46-26" tabindex="-1"></a><span class="fu">grid</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:species-accumulation-subplot"></span>
<img src="_main_files/figure-html/species-accumulation-subplot-1.png" alt="Species accumulation curve showing the cumulative discovery of species as the number of sampled subplots increases." width="672" />
<p class="caption">
Figure 3.3: Species accumulation curve showing the cumulative discovery of species as the number of sampled subplots increases.
</p>
</div>
<p><strong>Interpretation of the Sample-based accumulation rate</strong></p>
<p>While the previous curve measured sampling effort by individual stems, this Species Accumulation Curve visualizes richness against the number of spatial units (subplots) surveyed. Across the 100 subplots sampled, the cumulative species count climbs to 207. The curve (solid green line) remains steadily ascending, mirroring the lack of an asymptote seen in the individual-based curve. Notably, the 95% confidence interval (light green ribbon) is widest in the intermediate stages of sampling, highlighting significant variability in the number of new species contributed by each randomly added subplot.</p>
<p><strong><em>Ecological theory and context </em></strong></p>
<p>In forest ecology, comparing an individual-based accumulation curve with a sample-based (subplot) accumulation curve is crucial because it introduces the dimension of physical space. Individual-based models mathematically assume that trees are randomly mixed throughout the forest like a well-shuffled deck of cards. However, this subplot-based curve captures the reality of how forests are actually structured on the ground.<span class="citation"><a href="#fn31" class="footnote-ref" id="fnref31"><sup>31</sup></a></span></p>
<p>The persistent upward climb and the variability in this spatial curve are driven by two key ecological mechanisms:</p>
<ul>
<li><p>Spatial aggregation (Clumping): In tropical forests, tree species are rarely distributed evenly. Instead, they exhibit highly clumped or aggregated spatial patterns, primarily due to dispersal limitation (where heavy seeds drop and germinate close to the parent tree) and localized gap dynamics.<span class="citation"><a href="#fn32" class="footnote-ref" id="fnref32"><sup>32</sup></a></span> Because rare species are clustered, moving the survey into a new subplot often means stumbling into a completely new, localized pocket of taxa that were absent in all previously sampled units.</p></li>
<li><p>Beta diversity and microhabitats: As the sampling effort expands across 100 subplots, it inevitably traverses subtle environmental gradients—such as slight shifts in topography, soil moisture, or localized nutrient availability. This spatial turnover of species from one subplot to the next (beta diversity) means the physical expansion of the sampling area continuously introduces new habitat niches, bringing new specialist species into the cumulative inventory.</p></li>
</ul>
<p>Ultimately, this plot confirms that the forest stand is not only hyper-diverse but structurally highly heterogeneous. For researchers, this demonstrates why large, contiguous sampling plots (or extensive subplot networks) are mandatory for accurately capturing carbon and biomass attributes in the Amazon, as small or highly localized plots will drastically underestimate community complexity.</p>
</div>
<div id="synthesis-of-structure-and-composition-the-importance-value-index-ivi" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Synthesis of Structure and Composition: The Importance Value Index (IVI)<a href="chapter-3-forest-composition-structure.html#synthesis-of-structure-and-composition-the-importance-value-index-ivi" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ecological Theory and ContextIn tropical forest analysis, evaluating a species based on a single metric can lead to severe ecological misinterpretations. For example, a highly abundant understory shrub might dominate the stand in pure stem count (Density) but contribute almost nothing to the physical architecture of the forest. Conversely, a massive canopy emergent might have a massive footprint (Basal Area) but be so rare that it is only represented by a single individual.</p>
<p>To resolve this, ecologists use the Importance Value Index (IVI), a foundational metric developed by Curtis and McIntosh (1951). The IVI synthesizes both composition and structure into a single numerical value, allowing us to rank the true ecological dominance and structural influence of each species within the community.</p>
<p>The index is calculated by summing three relative metrics (each expressed as a percentage of the stand total):</p>
<ul>
<li><p>Relative Density (Composition): The number of individuals of a species divided by the total number of individuals of all species. This captures numerical abundance.</p></li>
<li><p>Relative Frequency (Spatial Distribution): The number of subplots (or quadrats) in which a species occurs divided by the total occurrences of all species. This captures spatial dispersion, ensuring that a species clumped in only one corner of the plot does not artificially skew the index.</p></li>
<li><p>Relative Dominance (Structure): The total basal area of a species divided by the total basal area of all species. This captures the physical and structural footprint of the taxa.</p></li>
</ul>
<p><strong><em>Mathematical Formulation</em></strong>
The IVI for any given species is expressed as:</p>
<p><span class="math display">\[IVI = Relative Density + Relative Frequency + Relative Dominance\]</span>
<strong><em>(Note: Because each component is a percentage out of 100, the maximum possible IVI for a monoculture stand is 300).</em></strong></p>
<p>Relevance to Amazonian DynamicsIn hyper-diverse Amazonian ecosystems, the IVI is the ultimate mathematical test of the Hyperdominance theory.<span class="citation"><a href="#fn33" class="footnote-ref" id="fnref33"><sup>33</sup></a></span> When we calculate the IVI for this stand, the species that score the highest are not necessarily the most numerous, nor the largest. Rather, they are the “oligarchs” of the forest—species that successfully recruit in high numbers, spread widely across the landscape, and accumulate enough basal area to dictate the competitive dynamics, light availability, and carbon storage of the ecosystem.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="chapter-3-forest-composition-structure.html#cb47-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb47-2"><a href="chapter-3-forest-composition-structure.html#cb47-2" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb47-3"><a href="chapter-3-forest-composition-structure.html#cb47-3" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb47-4"><a href="chapter-3-forest-composition-structure.html#cb47-4" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb47-5"><a href="chapter-3-forest-composition-structure.html#cb47-5" tabindex="-1"></a></span>
<span id="cb47-6"><a href="chapter-3-forest-composition-structure.html#cb47-6" tabindex="-1"></a><span class="co"># 1. Calculate individual Basal Area (BA) in square meters</span></span>
<span id="cb47-7"><a href="chapter-3-forest-composition-structure.html#cb47-7" tabindex="-1"></a>inventory_ivi <span class="ot">&lt;-</span> inventory_clean <span class="sc">%&gt;%</span></span>
<span id="cb47-8"><a href="chapter-3-forest-composition-structure.html#cb47-8" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">BA_m2 =</span> pi <span class="sc">*</span> (DBH_cm <span class="sc">/</span> <span class="dv">200</span>)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb47-9"><a href="chapter-3-forest-composition-structure.html#cb47-9" tabindex="-1"></a></span>
<span id="cb47-10"><a href="chapter-3-forest-composition-structure.html#cb47-10" tabindex="-1"></a><span class="co"># 2. Calculate Absolute Metrics per Species</span></span>
<span id="cb47-11"><a href="chapter-3-forest-composition-structure.html#cb47-11" tabindex="-1"></a>species_summary <span class="ot">&lt;-</span> inventory_ivi <span class="sc">%&gt;%</span></span>
<span id="cb47-12"><a href="chapter-3-forest-composition-structure.html#cb47-12" tabindex="-1"></a>  <span class="fu">group_by</span>(Scientific_Name) <span class="sc">%&gt;%</span></span>
<span id="cb47-13"><a href="chapter-3-forest-composition-structure.html#cb47-13" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb47-14"><a href="chapter-3-forest-composition-structure.html#cb47-14" tabindex="-1"></a>    <span class="at">Count =</span> <span class="fu">n</span>(),                                      <span class="co"># Absolute Density</span></span>
<span id="cb47-15"><a href="chapter-3-forest-composition-structure.html#cb47-15" tabindex="-1"></a>    <span class="at">Sum_BA =</span> <span class="fu">sum</span>(BA_m2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),                <span class="co"># Absolute Dominance</span></span>
<span id="cb47-16"><a href="chapter-3-forest-composition-structure.html#cb47-16" tabindex="-1"></a>    <span class="at">Subplots_Present =</span> <span class="fu">n_distinct</span>(Plot_ID)            <span class="co"># Absolute Frequency</span></span>
<span id="cb47-17"><a href="chapter-3-forest-composition-structure.html#cb47-17" tabindex="-1"></a>  )</span>
<span id="cb47-18"><a href="chapter-3-forest-composition-structure.html#cb47-18" tabindex="-1"></a></span>
<span id="cb47-19"><a href="chapter-3-forest-composition-structure.html#cb47-19" tabindex="-1"></a><span class="co"># 3. Calculate Relative Metrics and the final IVI</span></span>
<span id="cb47-20"><a href="chapter-3-forest-composition-structure.html#cb47-20" tabindex="-1"></a>ivi_table <span class="ot">&lt;-</span> species_summary <span class="sc">%&gt;%</span></span>
<span id="cb47-21"><a href="chapter-3-forest-composition-structure.html#cb47-21" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb47-22"><a href="chapter-3-forest-composition-structure.html#cb47-22" tabindex="-1"></a>    <span class="at">Rel_Density   =</span> (Count <span class="sc">/</span> <span class="fu">sum</span>(Count)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb47-23"><a href="chapter-3-forest-composition-structure.html#cb47-23" tabindex="-1"></a>    <span class="at">Rel_Dominance =</span> (Sum_BA <span class="sc">/</span> <span class="fu">sum</span>(Sum_BA)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb47-24"><a href="chapter-3-forest-composition-structure.html#cb47-24" tabindex="-1"></a>    <span class="at">Rel_Frequency =</span> (Subplots_Present <span class="sc">/</span> <span class="fu">sum</span>(Subplots_Present)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb47-25"><a href="chapter-3-forest-composition-structure.html#cb47-25" tabindex="-1"></a>    <span class="at">IVI           =</span> Rel_Density <span class="sc">+</span> Rel_Dominance <span class="sc">+</span> Rel_Frequency</span>
<span id="cb47-26"><a href="chapter-3-forest-composition-structure.html#cb47-26" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb47-27"><a href="chapter-3-forest-composition-structure.html#cb47-27" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(IVI))</span>
<span id="cb47-28"><a href="chapter-3-forest-composition-structure.html#cb47-28" tabindex="-1"></a></span>
<span id="cb47-29"><a href="chapter-3-forest-composition-structure.html#cb47-29" tabindex="-1"></a><span class="co"># 4. Generate the table</span></span>
<span id="cb47-30"><a href="chapter-3-forest-composition-structure.html#cb47-30" tabindex="-1"></a>ivi_table <span class="sc">%&gt;%</span></span>
<span id="cb47-31"><a href="chapter-3-forest-composition-structure.html#cb47-31" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb47-32"><a href="chapter-3-forest-composition-structure.html#cb47-32" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>, </span>
<span id="cb47-33"><a href="chapter-3-forest-composition-structure.html#cb47-33" tabindex="-1"></a>        <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">&quot;Species&quot;</span>, <span class="st">&quot;N&quot;</span>, <span class="st">&quot;Total BA (m2)&quot;</span>, <span class="st">&quot;Plots Present&quot;</span>, </span>
<span id="cb47-34"><a href="chapter-3-forest-composition-structure.html#cb47-34" tabindex="-1"></a>                      <span class="st">&quot;Rel. Density (%)&quot;</span>, <span class="st">&quot;Rel. Dominance (%)&quot;</span>, <span class="st">&quot;Rel. Frequency (%)&quot;</span>, <span class="st">&quot;IVI&quot;</span>),</span>
<span id="cb47-35"><a href="chapter-3-forest-composition-structure.html#cb47-35" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">&quot;Importance value index (IVI) of the top 10 most structurally dominant species in the stand.&quot;</span>)</span></code></pre></div>
<table style="width:100%;">
<caption><span id="tab:calculate-ivi">Table 3.1: </span>Importance value index (IVI) of the top 10 most structurally dominant species in the stand.</caption>
<colgroup>
<col width="19%" />
<col width="2%" />
<col width="12%" />
<col width="12%" />
<col width="14%" />
<col width="16%" />
<col width="16%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Species</th>
<th align="right">N</th>
<th align="right">Total BA (m2)</th>
<th align="right">Plots Present</th>
<th align="right">Rel. Density (%)</th>
<th align="right">Rel. Dominance (%)</th>
<th align="right">Rel. Frequency (%)</th>
<th align="right">IVI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Pouteria guianensis</td>
<td align="right">35</td>
<td align="right">1.62</td>
<td align="right">30</td>
<td align="right">5.14</td>
<td align="right">6.30</td>
<td align="right">4.75</td>
<td align="right">16.19</td>
</tr>
<tr class="even">
<td align="left">Inga ruiziana</td>
<td align="right">28</td>
<td align="right">1.09</td>
<td align="right">23</td>
<td align="right">4.11</td>
<td align="right">4.22</td>
<td align="right">3.64</td>
<td align="right">11.97</td>
</tr>
<tr class="odd">
<td align="left">Virola duckei</td>
<td align="right">29</td>
<td align="right">0.84</td>
<td align="right">23</td>
<td align="right">4.26</td>
<td align="right">3.27</td>
<td align="right">3.64</td>
<td align="right">11.16</td>
</tr>
<tr class="even">
<td align="left">Protium amazonicum</td>
<td align="right">30</td>
<td align="right">0.71</td>
<td align="right">25</td>
<td align="right">4.41</td>
<td align="right">2.78</td>
<td align="right">3.96</td>
<td align="right">11.14</td>
</tr>
<tr class="odd">
<td align="left">Perebea guianensis</td>
<td align="right">24</td>
<td align="right">0.97</td>
<td align="right">21</td>
<td align="right">3.52</td>
<td align="right">3.75</td>
<td align="right">3.32</td>
<td align="right">10.60</td>
</tr>
<tr class="even">
<td align="left">Eschweilera albiflora</td>
<td align="right">19</td>
<td align="right">0.74</td>
<td align="right">17</td>
<td align="right">2.79</td>
<td align="right">2.88</td>
<td align="right">2.69</td>
<td align="right">8.36</td>
</tr>
<tr class="odd">
<td align="left">Guatteria elata</td>
<td align="right">20</td>
<td align="right">0.56</td>
<td align="right">19</td>
<td align="right">2.94</td>
<td align="right">2.18</td>
<td align="right">3.01</td>
<td align="right">8.13</td>
</tr>
<tr class="even">
<td align="left">Guarea guidonia</td>
<td align="right">23</td>
<td align="right">0.40</td>
<td align="right">20</td>
<td align="right">3.38</td>
<td align="right">1.57</td>
<td align="right">3.16</td>
<td align="right">8.11</td>
</tr>
<tr class="odd">
<td align="left">Pourouma ovata</td>
<td align="right">9</td>
<td align="right">1.22</td>
<td align="right">9</td>
<td align="right">1.32</td>
<td align="right">4.75</td>
<td align="right">1.42</td>
<td align="right">7.50</td>
</tr>
<tr class="even">
<td align="left">Astrocaryum murumuru</td>
<td align="right">16</td>
<td align="right">0.51</td>
<td align="right">14</td>
<td align="right">2.35</td>
<td align="right">1.99</td>
<td align="right">2.22</td>
<td align="right">6.56</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="chapter-3-forest-composition-structure.html#cb48-1" tabindex="-1"></a><span class="co"># 5. Prepare data for the stacked bar chart</span></span>
<span id="cb48-2"><a href="chapter-3-forest-composition-structure.html#cb48-2" tabindex="-1"></a>ivi_plot_data <span class="ot">&lt;-</span> ivi_table <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="chapter-3-forest-composition-structure.html#cb48-3" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-4"><a href="chapter-3-forest-composition-structure.html#cb48-4" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb48-5"><a href="chapter-3-forest-composition-structure.html#cb48-5" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(Rel_Density, Rel_Dominance, Rel_Frequency),</span>
<span id="cb48-6"><a href="chapter-3-forest-composition-structure.html#cb48-6" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;Metric&quot;</span>,</span>
<span id="cb48-7"><a href="chapter-3-forest-composition-structure.html#cb48-7" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;Percentage&quot;</span></span>
<span id="cb48-8"><a href="chapter-3-forest-composition-structure.html#cb48-8" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb48-9"><a href="chapter-3-forest-composition-structure.html#cb48-9" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Metric =</span> <span class="fu">recode</span>(Metric, </span>
<span id="cb48-10"><a href="chapter-3-forest-composition-structure.html#cb48-10" tabindex="-1"></a>                         <span class="st">&quot;Rel_Density&quot;</span> <span class="ot">=</span> <span class="st">&quot;Relative Density&quot;</span>,</span>
<span id="cb48-11"><a href="chapter-3-forest-composition-structure.html#cb48-11" tabindex="-1"></a>                         <span class="st">&quot;Rel_Dominance&quot;</span> <span class="ot">=</span> <span class="st">&quot;Relative Dominance&quot;</span>,</span>
<span id="cb48-12"><a href="chapter-3-forest-composition-structure.html#cb48-12" tabindex="-1"></a>                         <span class="st">&quot;Rel_Frequency&quot;</span> <span class="ot">=</span> <span class="st">&quot;Relative Frequency&quot;</span>))</span>
<span id="cb48-13"><a href="chapter-3-forest-composition-structure.html#cb48-13" tabindex="-1"></a></span>
<span id="cb48-14"><a href="chapter-3-forest-composition-structure.html#cb48-14" tabindex="-1"></a><span class="co"># 6. Generate the IVI component plot with percentage labels</span></span>
<span id="cb48-15"><a href="chapter-3-forest-composition-structure.html#cb48-15" tabindex="-1"></a><span class="fu">ggplot</span>(ivi_plot_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Scientific_Name, IVI), <span class="at">y =</span> Percentage, <span class="at">fill =</span> Metric)) <span class="sc">+</span></span>
<span id="cb48-16"><a href="chapter-3-forest-composition-structure.html#cb48-16" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">linewidth =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb48-17"><a href="chapter-3-forest-composition-structure.html#cb48-17" tabindex="-1"></a>  </span>
<span id="cb48-18"><a href="chapter-3-forest-composition-structure.html#cb48-18" tabindex="-1"></a>  <span class="co"># Add the text labels inside the stacked bars</span></span>
<span id="cb48-19"><a href="chapter-3-forest-composition-structure.html#cb48-19" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb48-20"><a href="chapter-3-forest-composition-structure.html#cb48-20" tabindex="-1"></a>    <span class="fu">aes</span>(</span>
<span id="cb48-21"><a href="chapter-3-forest-composition-structure.html#cb48-21" tabindex="-1"></a>      <span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">&quot;%.1f%%&quot;</span>, Percentage), <span class="co"># Formats the number to 1 decimal place with a % sign</span></span>
<span id="cb48-22"><a href="chapter-3-forest-composition-structure.html#cb48-22" tabindex="-1"></a>      <span class="at">color =</span> Metric                         <span class="co"># Maps text color to the metric to handle light/dark contrast</span></span>
<span id="cb48-23"><a href="chapter-3-forest-composition-structure.html#cb48-23" tabindex="-1"></a>    ),</span>
<span id="cb48-24"><a href="chapter-3-forest-composition-structure.html#cb48-24" tabindex="-1"></a>    <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>),  <span class="co"># Centers the text inside each stacked section</span></span>
<span id="cb48-25"><a href="chapter-3-forest-composition-structure.html#cb48-25" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">3.5</span>, </span>
<span id="cb48-26"><a href="chapter-3-forest-composition-structure.html#cb48-26" tabindex="-1"></a>    <span class="at">fontface =</span> <span class="st">&quot;bold&quot;</span>,</span>
<span id="cb48-27"><a href="chapter-3-forest-composition-structure.html#cb48-27" tabindex="-1"></a>    <span class="at">show.legend =</span> <span class="cn">FALSE</span>                      <span class="co"># Hides the text &#39;a&#39; from the legend</span></span>
<span id="cb48-28"><a href="chapter-3-forest-composition-structure.html#cb48-28" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb48-29"><a href="chapter-3-forest-composition-structure.html#cb48-29" tabindex="-1"></a>  </span>
<span id="cb48-30"><a href="chapter-3-forest-composition-structure.html#cb48-30" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb48-31"><a href="chapter-3-forest-composition-structure.html#cb48-31" tabindex="-1"></a>  </span>
<span id="cb48-32"><a href="chapter-3-forest-composition-structure.html#cb48-32" tabindex="-1"></a>  <span class="co"># Bar fill colors (Colorblind-safe Viridis)</span></span>
<span id="cb48-33"><a href="chapter-3-forest-composition-structure.html#cb48-33" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb48-34"><a href="chapter-3-forest-composition-structure.html#cb48-34" tabindex="-1"></a>    <span class="st">&quot;Relative Density&quot;</span> <span class="ot">=</span> <span class="st">&quot;#440154&quot;</span>, </span>
<span id="cb48-35"><a href="chapter-3-forest-composition-structure.html#cb48-35" tabindex="-1"></a>    <span class="st">&quot;Relative Dominance&quot;</span> <span class="ot">=</span> <span class="st">&quot;#21908C&quot;</span>, </span>
<span id="cb48-36"><a href="chapter-3-forest-composition-structure.html#cb48-36" tabindex="-1"></a>    <span class="st">&quot;Relative Frequency&quot;</span> <span class="ot">=</span> <span class="st">&quot;#FDE725&quot;</span></span>
<span id="cb48-37"><a href="chapter-3-forest-composition-structure.html#cb48-37" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb48-38"><a href="chapter-3-forest-composition-structure.html#cb48-38" tabindex="-1"></a>  </span>
<span id="cb48-39"><a href="chapter-3-forest-composition-structure.html#cb48-39" tabindex="-1"></a>  <span class="co"># Text colors to contrast with the bar fills</span></span>
<span id="cb48-40"><a href="chapter-3-forest-composition-structure.html#cb48-40" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb48-41"><a href="chapter-3-forest-composition-structure.html#cb48-41" tabindex="-1"></a>    <span class="st">&quot;Relative Density&quot;</span> <span class="ot">=</span> <span class="st">&quot;white&quot;</span>, </span>
<span id="cb48-42"><a href="chapter-3-forest-composition-structure.html#cb48-42" tabindex="-1"></a>    <span class="st">&quot;Relative Dominance&quot;</span> <span class="ot">=</span> <span class="st">&quot;white&quot;</span>, </span>
<span id="cb48-43"><a href="chapter-3-forest-composition-structure.html#cb48-43" tabindex="-1"></a>    <span class="st">&quot;Relative Frequency&quot;</span> <span class="ot">=</span> <span class="st">&quot;black&quot;</span>     <span class="co"># Black text on the bright yellow background</span></span>
<span id="cb48-44"><a href="chapter-3-forest-composition-structure.html#cb48-44" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb48-45"><a href="chapter-3-forest-composition-structure.html#cb48-45" tabindex="-1"></a>  </span>
<span id="cb48-46"><a href="chapter-3-forest-composition-structure.html#cb48-46" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb48-47"><a href="chapter-3-forest-composition-structure.html#cb48-47" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Deconstructing structural dominance (Top 10 Species)&quot;</span>,</span>
<span id="cb48-48"><a href="chapter-3-forest-composition-structure.html#cb48-48" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">&quot;Components of the Importance Value Index (IVI)&quot;</span>,</span>
<span id="cb48-49"><a href="chapter-3-forest-composition-structure.html#cb48-49" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Scientific Name&quot;</span>,</span>
<span id="cb48-50"><a href="chapter-3-forest-composition-structure.html#cb48-50" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Relative Contribution (%)&quot;</span>,</span>
<span id="cb48-51"><a href="chapter-3-forest-composition-structure.html#cb48-51" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;IVI Component&quot;</span></span>
<span id="cb48-52"><a href="chapter-3-forest-composition-structure.html#cb48-52" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb48-53"><a href="chapter-3-forest-composition-structure.html#cb48-53" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb48-54"><a href="chapter-3-forest-composition-structure.html#cb48-54" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb48-55"><a href="chapter-3-forest-composition-structure.html#cb48-55" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;italic&quot;</span>, <span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb48-56"><a href="chapter-3-forest-composition-structure.html#cb48-56" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>,</span>
<span id="cb48-57"><a href="chapter-3-forest-composition-structure.html#cb48-57" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>)</span>
<span id="cb48-58"><a href="chapter-3-forest-composition-structure.html#cb48-58" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/calculate-ivi-1.png" alt="" width="768" />
*<strong>Interpretation of the Importance Value Index (IVI)</strong></p>
<p>*<strong>Visual and tabular observations</strong>
The combination of the data table and the stacked bar chart perfectly deconstructs the ecological footprint of the top 10 taxa in the stand, revealing exactly how each species achieves its dominance.</p>
<ul>
<li><p>The ultimate oligarch: Pouteria guianensis clearly dominates the stand with an IVI of 16.19. The stacked bar chart illustrates that this dominance is highly balanced; it leads the community across all three components, boasting the highest Relative Density (5.14%), Relative Dominance (6.30%), and Relative Frequency (4.75%).</p></li>
<li><p>The midstory specialist: Protium amazonicum ranks fourth overall (IVI = 11.14). However, the visual deconstruction reveals its score is driven almost entirely by a high Relative Density (4.41%) and Frequency (3.96%), paired with a remarkably narrow Relative Dominance band (2.78%). This mathematically confirms our earlier spatial analysis: it is a highly numerous, widely dispersed, but physically small midstory species.</p></li>
<li><p>The canopy giant: Pourouma ovata provides the most striking structural contrast. Despite having a mere 9 individuals across 9 subplots (yielding extremely narrow purple and yellow bands in the chart), it secures the ninth-highest IVI in the stand (7.50). Its massive teal band highlights a Relative Dominance of 4.75%—the second highest in the entire plot—proving that these 9 rare stems are massive canopy emergents commanding immense basal area.</p></li>
</ul>
<p><strong><em>Ecological synthesis and carbon implications</em></strong></p>
<p>This IVI analysis acts as the definitive synthesis of the structural chapters. It proves mathematically that raw stem count is a poor proxy for overall ecosystem influence. In hyper-diverse Amazonian ecosystems, a handful of large-diameter taxa command a disproportionate share of the stand’s physical space, thereby dictating light interception, localized gap-phase dynamics, and aboveground carbon storage.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="20">
<li id="fn20"><p><span class="nocase">Hans ter Steege et al.</span>, <span>“Hyperdominance in the Amazonian Tree Flora,”</span> <em>Science</em> 342, no. 6156 (2013): 1243092, <a href="https://doi.org/10.1126/science.1243092">https://doi.org/10.1126/science.1243092</a>.<a href="chapter-3-forest-composition-structure.html#fnref20" class="footnote-back">↩︎</a></p></li>
<li id="fn21"><p>Nigel CA Pitman et al., <span>“Dominance and Distribution of Tree Species in Upper Amazonian Terra Firme Forests,”</span> <em>Ecology</em> 82, no. 8 (2001): 2101–17, <a href="https://doi.org/10.1890/0012-9658(2001)082%5B2101:DADOTS%5D2.0.CO;2">https://doi.org/10.1890/0012-9658(2001)082[2101:DADOTS]2.0.CO;2</a>.<a href="chapter-3-forest-composition-structure.html#fnref21" class="footnote-back">↩︎</a></p></li>
<li id="fn22"><p>Claude E Shannon, <span>“A Mathematical Theory of Communication,”</span> <em>The Bell System Technical Journal</em> 27, no. 3 (1948): 379–423; Anne E Magurran, <em>Measuring Biological Diversity</em> (John Wiley &amp; Sons, 2004).<a href="chapter-3-forest-composition-structure.html#fnref22" class="footnote-back">↩︎</a></p></li>
<li id="fn23"><p>Edward H Simpson, <span>“Measurement of Diversity,”</span> <em>Nature</em> 163, no. 4148 (1949): 688–88.<a href="chapter-3-forest-composition-structure.html#fnref23" class="footnote-back">↩︎</a></p></li>
<li id="fn24"><p>Anne E Magurran, <em>Measuring Biological Diversity</em> (Blackwell Science, 2004).<a href="chapter-3-forest-composition-structure.html#fnref24" class="footnote-back">↩︎</a></p></li>
<li id="fn25"><p>Renato Valencia et al., <span>“High Tree Alpha-Diversity in Amazonian Ecuador,”</span> <em>Biodiversity &amp; Conservation</em> 3, no. 1 (1994): 21–28, <a href="https://doi.org/10.1007/BF00115330">https://doi.org/10.1007/BF00115330</a>.<a href="chapter-3-forest-composition-structure.html#fnref25" class="footnote-back">↩︎</a></p></li>
<li id="fn26"><p>Daniel H Janzen, <span>“Herbivores and the Number of Tree Species in Tropical Forests,”</span> <em>The American Naturalist</em> 104, no. 940 (1970): 501–28, <a href="https://doi.org/10.1086/282687">https://doi.org/10.1086/282687</a>.<a href="chapter-3-forest-composition-structure.html#fnref26" class="footnote-back">↩︎</a></p></li>
<li id="fn27"><p>Magurran, <em>Measuring Biological Diversity</em> (Blackwell Science, 2004).<a href="chapter-3-forest-composition-structure.html#fnref27" class="footnote-back">↩︎</a></p></li>
<li id="fn28"><p>Richard Condit et al., <span>“Species-Area and Species-Individual Relationships for Tropical Trees: A Comparison of Three 50-Ha Plots,”</span> <em>Journal of Ecology</em> 84, no. 4 (1996): 549–62, <a href="https://doi.org/10.2307/2261477">https://doi.org/10.2307/2261477</a>.<a href="chapter-3-forest-composition-structure.html#fnref28" class="footnote-back">↩︎</a></p></li>
<li id="fn29"><p>Nicholas J Gotelli and Robert K Colwell, <span>“Quantifying Biodiversity: Procedures and Pitfalls in the Measurement and Comparison of Species Richness,”</span> <em>Ecology Letters</em> 4, no. 4 (2001): 379–91, <a href="https://doi.org/10.1046/j.1461-0248.2001.00230.x">https://doi.org/10.1046/j.1461-0248.2001.00230.x</a>.<a href="chapter-3-forest-composition-structure.html#fnref29" class="footnote-back">↩︎</a></p></li>
<li id="fn30"><p>Gotelli and Colwell, <span>“Quantifying Biodiversity.”</span><a href="chapter-3-forest-composition-structure.html#fnref30" class="footnote-back">↩︎</a></p></li>
<li id="fn31"><p>Gotelli and Colwell, <span>“Quantifying Biodiversity.”</span><a href="chapter-3-forest-composition-structure.html#fnref31" class="footnote-back">↩︎</a></p></li>
<li id="fn32"><p><span class="nocase">Condit et al.</span>, <span>“Spatial Patterns in the Distribution of Tropical Tree Species.”</span><a href="chapter-3-forest-composition-structure.html#fnref32" class="footnote-back">↩︎</a></p></li>
<li id="fn33"><p><span class="nocase">Steege et al.</span>, <span>“Hyperdominance in the Amazonian Tree Flora.”</span><a href="chapter-3-forest-composition-structure.html#fnref33" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
<script src="https://giscus.app/client.js"
        data-repo="jdurquizam/ForestAR"
        data-repo-id="R_kgDOQALDvA"
        data-category="General"
        data-category-id="DIC_kwDOQALDvM4DFUqb"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="dark_tritanopia"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>
            </section>

          </div>
        </div>
      </div>
<a href="chapter-2-forest-stand-structure.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter-4-allometric-relationships-and-statistical-correlation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "sepia",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
