<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Chapter 3: Forest Stand Structure | _main.knit</title>
  <meta name="description" content="This short book should help you to get a better understanding of how the forest attributes analysis works, what you might want to consider in order to perform that are applicable for their respective purpose." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Chapter 3: Forest Stand Structure | _main.knit" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://doi.org/10.5281/zenodo.22606690/fig/MPG_Logo_green.png" />
  <meta property="og:description" content="This short book should help you to get a better understanding of how the forest attributes analysis works, what you might want to consider in order to perform that are applicable for their respective purpose." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Chapter 3: Forest Stand Structure | _main.knit" />
  
  <meta name="twitter:description" content="This short book should help you to get a better understanding of how the forest attributes analysis works, what you might want to consider in order to perform that are applicable for their respective purpose." />
  <meta name="twitter:image" content="https://doi.org/10.5281/zenodo.22606690/fig/MPG_Logo_green.png" />

<meta name="author" content="J. David Urquiza-Munoz" />


<meta name="date" content="2026-09-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chapter-1-introduction-to-forest-data-in-r.html"/>
<link rel="next" href="chapter-2-forest-composition-structure.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/rglWebGL-binding-1.3.36/rglWebGL.js"></script>
<link href="libs/rglwidgetClass-1.3.36/rgl.css" rel="stylesheet" />
<script src="libs/rglwidgetClass-1.3.36/rglClass.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/utils.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/buffer.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/subscenes.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/shaders.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/shadersrc.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/textures.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/projection.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/mouse.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/init.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/pieces.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/draw.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/controls.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/selection.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/rglTimer.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/pretty.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/axes.src.js"></script>
<script src="libs/rglwidgetClass-1.3.36/animation.src.js"></script>
<script src="libs/CanvasMatrix4-1.3.36/CanvasMatrix.src.js"></script>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FMG5FF37YL"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FMG5FF37YL');
</script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-this-book"><i class="fa fa-check"></i>About this book</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-cite-this-book"><i class="fa fa-check"></i>How to Cite this Book</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the author</a>
<ul>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html#j.-david-urquiza-mu%C3%B1oz"><i class="fa fa-check"></i>J. David Urquiza Muñoz</a>
<ul>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html#for-more-information-about-the-author-visit-his-personal-website"><i class="fa fa-check"></i><strong>For more information about the author, visit his personal website:</strong></a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html#httpsjdurquizam.github.io"><i class="fa fa-check"></i><em>https://jdurquizam.github.io/</em></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html"><i class="fa fa-check"></i><b>1</b> Chapter 1: Introduction to Forest Data in R</a>
<ul>
<li class="chapter" data-level="1.0.1" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#download-project-files"><i class="fa fa-check"></i><b>1.0.1</b> Download Project Files</a></li>
<li class="chapter" data-level="1.1" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#setting-your-working-directory"><i class="fa fa-check"></i><b>1.1</b> Setting Your Working Directory</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#using-rstudio-projects"><i class="fa fa-check"></i><b>1.1.1</b> Using RStudio Projects</a></li>
<li class="chapter" data-level="1.1.2" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#using-the-here-package"><i class="fa fa-check"></i><b>1.1.2</b> Using the <code>here</code> Package</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#setting-up-the-environment"><i class="fa fa-check"></i><b>1.2</b> Setting up the Environment</a></li>
<li class="chapter" data-level="1.3" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#importing-the-inventory-data"><i class="fa fa-check"></i><b>1.3</b> Importing the Inventory Data</a></li>
<li class="chapter" data-level="1.4" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#data-cleaning-and-standardization"><i class="fa fa-check"></i><b>1.4</b> Data Cleaning and Standardization</a></li>
<li class="chapter" data-level="1.5" data-path="chapter-1-introduction-to-forest-data-in-r.html"><a href="chapter-1-introduction-to-forest-data-in-r.html#exploring-the-cleaned-data"><i class="fa fa-check"></i><b>1.5</b> Exploring the Cleaned Data</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html"><i class="fa fa-check"></i><b>2</b> Chapter 3: Forest Stand Structure</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#diameter-at-breast-height-dbh"><i class="fa fa-check"></i><b>2.1</b> Diameter at Breast Height (DBH)</a></li>
<li class="chapter" data-level="2.2" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#stand-level-metrics-density-and-basal-area-per-hectare"><i class="fa fa-check"></i><b>2.2</b> Stand-Level Metrics: Density and Basal Area (Per Hectare)</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#quantitative-stand-metrics"><i class="fa fa-check"></i><b>2.2.1</b> Quantitative Stand Metrics</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#structural-composition-dbh-by-dominant-species"><i class="fa fa-check"></i><b>2.3</b> Structural Composition: DBH by Dominant Species</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#structural-roles-of-dominant-species"><i class="fa fa-check"></i><b>2.3.1</b> Structural Roles of Dominant Species</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#d-spatial-distribution-and-mapping"><i class="fa fa-check"></i><b>2.4</b> 2D Spatial Distribution and Mapping</a></li>
<li class="chapter" data-level="2.5" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#creating-spatial-data"><i class="fa fa-check"></i><b>2.5</b> Creating Spatial Data</a></li>
<li class="chapter" data-level="2.6" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#advanced-spatial-structure-point-pattern-analysis-by-species"><i class="fa fa-check"></i><b>2.6</b> Advanced Spatial Structure: Point Pattern Analysis by Species</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#mapping-forest-structure"><i class="fa fa-check"></i><b>2.6.1</b> Mapping Forest Structure</a></li>
<li class="chapter" data-level="2.6.2" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#visualizing-species-distribution"><i class="fa fa-check"></i><b>2.6.2</b> Visualizing Species Distribution</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#analyzing-spatial-clustering-with-the-morisita-index"><i class="fa fa-check"></i><b>2.7</b> Analyzing Spatial Clustering with the Morisita Index</a></li>
<li class="chapter" data-level="2.8" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#spatial-visualization-of-dbh-and-tree-height"><i class="fa fa-check"></i><b>2.8</b> Spatial Visualization of DBH and tree height</a></li>
<li class="chapter" data-level="2.9" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#biomass-and-carbon-as-structural-attributes"><i class="fa fa-check"></i><b>2.9</b> Biomass and carbon as structural attributes</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#extracting-wood-density-and-calculating-agb"><i class="fa fa-check"></i><b>2.9.1</b> Extracting Wood Density and Calculating AGB</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="chapter-3-forest-stand-structure.html"><a href="chapter-3-forest-stand-structure.html#spatial-distribution-of-carbon"><i class="fa fa-check"></i><b>2.10</b> Spatial distribution of carbon</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter-2-forest-composition-structure.html"><a href="chapter-2-forest-composition-structure.html"><i class="fa fa-check"></i><b>3</b> Chapter 2: Forest Composition &amp; Structure</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chapter-2-forest-composition-structure.html"><a href="chapter-2-forest-composition-structure.html#species-composition"><i class="fa fa-check"></i><b>3.1</b> Species Composition</a></li>
<li class="chapter" data-level="3.2" data-path="chapter-2-forest-composition-structure.html"><a href="chapter-2-forest-composition-structure.html#quantifying-biodiversity-diversity-indices"><i class="fa fa-check"></i><b>3.2</b> Quantifying biodiversity: diversity indices</a></li>
<li class="chapter" data-level="3.3" data-path="chapter-2-forest-composition-structure.html"><a href="chapter-2-forest-composition-structure.html#species-accumulation-curves"><i class="fa fa-check"></i><b>3.3</b> Species accumulation curves</a></li>
<li class="chapter" data-level="3.4" data-path="chapter-2-forest-composition-structure.html"><a href="chapter-2-forest-composition-structure.html#synthesis-of-structure-and-composition-the-importance-value-index-ivi"><i class="fa fa-check"></i><b>3.4</b> Synthesis of Structure and Composition: The Importance Value Index (IVI)</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapter-4-allometric-relationships-and-statistical-correlation.html"><a href="chapter-4-allometric-relationships-and-statistical-correlation.html"><i class="fa fa-check"></i><b>4</b> Chapter 4: Allometric Relationships and Statistical Correlation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chapter-4-allometric-relationships-and-statistical-correlation.html"><a href="chapter-4-allometric-relationships-and-statistical-correlation.html#allometric-relationships-and-statistical-correlation"><i class="fa fa-check"></i><b>4.1</b> Allometric Relationships and Statistical Correlation</a></li>
<li class="chapter" data-level="4.2" data-path="chapter-4-allometric-relationships-and-statistical-correlation.html"><a href="chapter-4-allometric-relationships-and-statistical-correlation.html#mathematical-models"><i class="fa fa-check"></i><b>4.2</b> Mathematical Models</a></li>
<li class="chapter" data-level="4.3" data-path="chapter-4-allometric-relationships-and-statistical-correlation.html"><a href="chapter-4-allometric-relationships-and-statistical-correlation.html#visualizing-the-correlation"><i class="fa fa-check"></i><b>4.3</b> Visualizing the Correlation</a></li>
<li class="chapter" data-level="4.4" data-path="chapter-4-allometric-relationships-and-statistical-correlation.html"><a href="chapter-4-allometric-relationships-and-statistical-correlation.html#estimating-missing-heights"><i class="fa fa-check"></i><b>4.4</b> Estimating Missing Heights</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><i class="fa fa-check"></i><b>5</b> Chapter 5: Canopy Gap Dynamics using 3D LiDAR</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#point-cloud-import-and-preprocessing"><i class="fa fa-check"></i><b>5.1</b> Point cloud import and preprocessing</a></li>
<li class="chapter" data-level="5.2" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#point-cloud-normalization"><i class="fa fa-check"></i><b>5.2</b> Point Cloud Normalization</a></li>
<li class="chapter" data-level="5.3" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#d-visualization"><i class="fa fa-check"></i><b>5.3</b> 3D visualization</a></li>
<li class="chapter" data-level="5.4" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#canopy-height-model-chm-generation"><i class="fa fa-check"></i><b>5.4</b> Canopy Height Model (CHM) Generation</a></li>
<li class="chapter" data-level="5.5" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#canopy-gap-detection-and-delineation"><i class="fa fa-check"></i><b>5.5</b> Canopy Gap Detection and Delineation</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="chapter-5-canopy-gap-dynamics-using-3d-lidar.html"><a href="chapter-5-canopy-gap-dynamics-using-3d-lidar.html#vertical-point-density-profile"><i class="fa fa-check"></i><b>5.5.1</b> Vertical Point Density Profile</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>6</b> References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><p><img src="fig/ForestAR_logo.jpg" style="width:8in" /></p>
<p>Forest Attributes Analysis in R - ForestAR</p></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="google_translate_element" style="padding: 10px; text-align: right;"></div>
<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({
    pageLanguage: 'en', 
    includedLanguages: 'es,pt',
    layout: google.translate.TranslateElement.InlineLayout.SIMPLE
  }, 'google_translate_element');
}
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

<div style="padding: 10px; text-align: center; font-size: 0.85em; border-top: 1px solid rgba(0,0,0,0.1); margin-top: 10px;">
  <strong>Connect:</strong><br>
  <a href="https://www.researchgate.net/profile/J-David-Urquiza-Munoz?ev=hdr_xprf" target="_blank" style="margin: 0 3px;">ResearchGate</a> | 
  <a href="https://www.linkedin.com/in/j-david-urquiza-munoz-446bb223/" target="_blank" style="margin: 0 3px;">LinkedIn</a> | 
  <a href="https://x.com/JoDaUrMu1" target="_blank" style="margin: 0 3px;">X</a>
</div>
<div id="chapter-3-forest-stand-structure" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">2</span> Chapter 3: Forest Stand Structure<a href="chapter-3-forest-stand-structure.html#chapter-3-forest-stand-structure" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="diameter-at-breast-height-dbh" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Diameter at Breast Height (DBH)<a href="chapter-3-forest-stand-structure.html#diameter-at-breast-height-dbh" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The distribution of tree diameters is a key indicator of forest health, history, and successional stage. In natural, uneven-aged forests, we typically expect to see a “Reverse-J” curve. This means there are many small, young trees in the understory and progressively fewer large, older trees forming the upper canopy.</p>
<p>We can visualize this using a histogram of our DBH_cm column.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="chapter-3-forest-stand-structure.html#cb9-1" tabindex="-1"></a><span class="fu">ggplot</span>(inventory_clean, <span class="fu">aes</span>(<span class="at">x =</span> DBH_cm)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="chapter-3-forest-stand-structure.html#cb9-2" tabindex="-1"></a>  <span class="co"># We use a binwidth of 5 cm, which is standard for forestry DBH classes</span></span>
<span id="cb9-3"><a href="chapter-3-forest-stand-structure.html#cb9-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">&quot;forestgreen&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="chapter-3-forest-stand-structure.html#cb9-4" tabindex="-1"></a>  <span class="co"># Create dynamic x-axis breaks based on our actual data max</span></span>
<span id="cb9-5"><a href="chapter-3-forest-stand-structure.html#cb9-5" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fu">max</span>(inventory_clean<span class="sc">$</span>DBH_cm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb9-6"><a href="chapter-3-forest-stand-structure.html#cb9-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-7"><a href="chapter-3-forest-stand-structure.html#cb9-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Diameter Distribution of the Stand&quot;</span>,</span>
<span id="cb9-8"><a href="chapter-3-forest-stand-structure.html#cb9-8" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">&quot;The Reverse-J shape indicates an uneven-aged, regenerating forest&quot;</span>,</span>
<span id="cb9-9"><a href="chapter-3-forest-stand-structure.html#cb9-9" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Diameter at Breast Height (cm)&quot;</span>,</span>
<span id="cb9-10"><a href="chapter-3-forest-stand-structure.html#cb9-10" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Frequency (Number of Trees)&quot;</span></span>
<span id="cb9-11"><a href="chapter-3-forest-stand-structure.html#cb9-11" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-12"><a href="chapter-3-forest-stand-structure.html#cb9-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:dbh-distribution"></span>
<img src="_main_files/figure-html/dbh-distribution-1.png" alt="Diameter distribution showing a classic Reverse-J curve for a natural forest." width="672" />
<p class="caption">
Figure 2.1: Diameter distribution showing a classic Reverse-J curve for a natural forest.
</p>
</div>
<p><strong>Interpretation of Diameter Distribution (Stand Structure)</strong></p>
<p><strong><em>Plot observations </em></strong></p>
<p>This histogram visualizes the structural composition of the forest stand by grouping trees into Diameter at Breast Height (DBH) classes. The distribution exhibits a severe positive skew, with the vast majority of individual stems concentrated in the smallest size classes (primarily between 10 cm and 20 cm DBH). As diameter increases, the frequency of trees drops precipitously, forming a long right-hand tail with only a few massive individuals exceeding 70 cm DBH. As noted in the plot’s subtitle, this distinct, right-skewed shape is universally referred to as a “reverse-J” distribution.</p>
<p><strong><em>Ecological theory and context</em></strong></p>
<p>The reverse-J DBH distribution is one of the most fundamental structural signatures of a natural, undisturbed, uneven-aged tropical forest.<span class="citation"><a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></span> Mathematically, this demographic equilibrium is often modeled using a negative exponential function (e.g., <span class="math inline">\(N(D) = k e^{-aD}\)</span>), where the number of trees (<span class="math inline">\(N\)</span>) in a given diameter class (<span class="math inline">\(D\)</span>) declines at a constant rate.</p>
<p>This structural pattern is maintained by several interacting forest dynamics:</p>
<ul>
<li><p>Continuous recruitment and high mortality: The massive spike on the left side of the graph represents a continuous influx of recruitment. However, the steep drop-off indicates severe mortality rates in the understory. Most of these small stems will die due to intense competition for light and resources before they ever reach the canopy.</p></li>
<li><p>Gap-phase dynamics and disturbance: The survival of small trees into larger DBH classes is highly dependent on canopy openings. Localized disturbances—such as storm-driven windthrow events, branch falls, or the natural senescence of canopy giants—create critical light gaps. The small trees waiting in the understory (the 10-20 cm class) respond to these gaps, driving the regeneration cycle.<span class="citation"><a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></span></p></li>
<li><p>The biomass paradox (carbon implications): When transitioning from structural attributes to ecosystem functioning, this reverse-J curve presents a crucial paradox. While the smallest trees completely dominate the stand in terms of stem density, the extremely rare, large-diameter trees in the right-hand tail disproportionately dominate the stand’s Aboveground Biomass (AGB). In Amazonian ecosystems, these few large trees drive the bulk of the forest’s carbon storage capacity and significantly influence overarching gross primary production (GPP) and net ecosystem exchange (NEE).<span class="citation"><a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></span></p></li>
</ul>
<p>Accurately modeling this long tail is essential, as missing even a single massive tree in a field survey can drastically underestimate the carbon stock of the plot.</p>
</div>
<div id="stand-level-metrics-density-and-basal-area-per-hectare" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Stand-Level Metrics: Density and Basal Area (Per Hectare)<a href="chapter-3-forest-stand-structure.html#stand-level-metrics-density-and-basal-area-per-hectare" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Visualizing the trees is helpful, but foresters need hard numbers to compare this stand to others across the Amazon. We need to calculate Stand Density (stems per hectare, <span class="math inline">\(N\)</span>) and Total Basal Area (<span class="math inline">\(G\)</span>).If we assume your inventory data represents a standard 1-hectare plot (or if you know the exact area, you can divide by it), we can easily summarize these metrics.</p>
<div id="quantitative-stand-metrics" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Quantitative Stand Metrics<a href="chapter-3-forest-stand-structure.html#quantitative-stand-metrics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Beyond visualizing the distribution of tree sizes, it is critical to quantify the overall physical occupation of the forest. The two most fundamental stand-level metrics are Stand Density (total number of trees) and Total Basal Area (the total cross-sectional area of all tree trunks).</p>
<p>Basal Area (<span class="math inline">\(BA\)</span>) is the cross-sectional area of a tree trunk measured at breast height. It is a fundamental metric for understanding structural dominance and forest volume.<span class="citation"><a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a></span> To convert Diameter at Breast Height (<span class="math inline">\(DBH\)</span>) measured in centimeters to Basal Area in square meters (<span class="math inline">\(m^2\)</span>), we use the following geometric equation:</p>
<p><span class="math display">\[BA = \frac{\pi \times DBH^2}{40000}\]</span>
Let’s calculate the total stand metrics for our plot.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="chapter-3-forest-stand-structure.html#cb10-1" tabindex="-1"></a><span class="co"># Calculate individual Basal Area and summarize the stand</span></span>
<span id="cb10-2"><a href="chapter-3-forest-stand-structure.html#cb10-2" tabindex="-1"></a>stand_summary <span class="ot">&lt;-</span> inventory_clean <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="chapter-3-forest-stand-structure.html#cb10-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">BA_m2 =</span> (pi <span class="sc">*</span> DBH_cm<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="dv">40000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="chapter-3-forest-stand-structure.html#cb10-4" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb10-5"><a href="chapter-3-forest-stand-structure.html#cb10-5" tabindex="-1"></a>    <span class="at">Total_Stems =</span> <span class="fu">n</span>(),</span>
<span id="cb10-6"><a href="chapter-3-forest-stand-structure.html#cb10-6" tabindex="-1"></a>    <span class="at">Total_Basal_Area_m2 =</span> <span class="fu">sum</span>(BA_m2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb10-7"><a href="chapter-3-forest-stand-structure.html#cb10-7" tabindex="-1"></a>    <span class="at">Mean_DBH_cm =</span> <span class="fu">mean</span>(DBH_cm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb10-8"><a href="chapter-3-forest-stand-structure.html#cb10-8" tabindex="-1"></a>    <span class="at">Max_DBH_cm =</span> <span class="fu">max</span>(DBH_cm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-9"><a href="chapter-3-forest-stand-structure.html#cb10-9" tabindex="-1"></a>  )</span>
<span id="cb10-10"><a href="chapter-3-forest-stand-structure.html#cb10-10" tabindex="-1"></a></span>
<span id="cb10-11"><a href="chapter-3-forest-stand-structure.html#cb10-11" tabindex="-1"></a><span class="co"># Display as a neat table</span></span>
<span id="cb10-12"><a href="chapter-3-forest-stand-structure.html#cb10-12" tabindex="-1"></a><span class="fu">kable</span>(stand_summary, </span>
<span id="cb10-13"><a href="chapter-3-forest-stand-structure.html#cb10-13" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">&quot;Summary of stand-level structural metrics.&quot;</span>,</span>
<span id="cb10-14"><a href="chapter-3-forest-stand-structure.html#cb10-14" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">&quot;Total Stems (N)&quot;</span>, <span class="st">&quot;Basal Area (m²)&quot;</span>, <span class="st">&quot;Mean DBH (cm)&quot;</span>, <span class="st">&quot;Max DBH (cm)&quot;</span>),</span>
<span id="cb10-15"><a href="chapter-3-forest-stand-structure.html#cb10-15" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div>
<table>
<caption><span id="tab:stand-metrics">Table 2.1: </span>Summary of stand-level structural metrics.</caption>
<thead>
<tr class="header">
<th align="right">Total Stems (N)</th>
<th align="right">Basal Area (m²)</th>
<th align="right">Mean DBH (cm)</th>
<th align="right">Max DBH (cm)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">681</td>
<td align="right">25.74</td>
<td align="right">18.54</td>
<td align="right">70.6</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation of Stand-Level Structural metrics</strong></p>
<p><strong><em>Table observations</em></strong></p>
<p>The summary table provides the foundational numerical metrics for the sampled forest stand. A total of 681 individual stems (<span class="math inline">\(N\)</span>) collectively generate a Basal Area of 25.74 m². The Mean DBH sits at a relatively low 18.54 cm, which contrasts sharply with the Max DBH of 70.6 cm recorded for the largest tree in the plot.</p>
<p>****Ecological theory and context***</p>
<p>These aggregated figures translate the earlier visual distributions into standard forest mensuration metrics, confirming the structural integrity and maturity of the ecosystem:</p>
<ul>
<li><p>Stand density and maturity: Basal area (the cross-sectional area of all tree stems at breast height) is one of the most critical metrics in forest ecology, serving as a highly reliable, non-destructive proxy for stand volume and Aboveground Biomass (AGB). A basal area of approximately 25.7 m² is a textbook benchmark for mature, intact terra firme forests in the Amazon, which typically range between 25 and 35 m² per hectare.<span class="citation"><a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a></span></p></li>
<li><p>Validating the reverse-J Curve: The stark numerical contrast between the high total stem count (681) and the low mean DBH (18.54 cm) mathematically validates the reverse-J histogram analyzed previously. The statistical mean is heavily anchored by the massive influx of small, understory stems (10–20 cm class), proving that the stand is continuously regenerating rather than stagnating.</p></li>
<li><p>The carbon drivers: The presence of a tree reaching 70.6 cm in diameter highlights the immense ecological weight of canopy giants. While these large-diameter individuals are numerically rare within the 681 total stems, basal area scales with the square of the radius. Therefore, a single 70 cm tree contributes exponentially more to the 25.74 m² total than dozens of 10 cm saplings combined. As demonstrated by Fauset et al. (2015), this structural reality dictates Amazonian carbon cycling: a hyperdominant minority of large trees dictates the overarching carbon storage and flux capacity of the entire ecosystem.</p></li>
</ul>
</div>
</div>
<div id="structural-composition-dbh-by-dominant-species" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Structural Composition: DBH by Dominant Species<a href="chapter-3-forest-stand-structure.html#structural-composition-dbh-by-dominant-species" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The overall “Reverse-J” curve is useful, but it hides the fact that different species occupy different structural niches. Some species are restricted to the understory (small DBH), while others consistently emerge into the upper canopy (large DBH).</p>
<div id="structural-roles-of-dominant-species" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Structural Roles of Dominant Species<a href="chapter-3-forest-stand-structure.html#structural-roles-of-dominant-species" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The overall forest might follow a Reverse-J curve, but individual species often have distinct structural roles. Some are understory specialists that rarely exceed a small DBH, while others are canopy emergents.</p>
<p>We can visualize this by isolating our most abundant species and plotting their specific diameter distributions using density curves.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="chapter-3-forest-stand-structure.html#cb11-1" tabindex="-1"></a><span class="co"># Identify the top 4 species by abundance</span></span>
<span id="cb11-2"><a href="chapter-3-forest-stand-structure.html#cb11-2" tabindex="-1"></a>top_4_species <span class="ot">&lt;-</span> inventory_clean <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="chapter-3-forest-stand-structure.html#cb11-3" tabindex="-1"></a>  <span class="fu">count</span>(Scientific_Name) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="chapter-3-forest-stand-structure.html#cb11-4" tabindex="-1"></a>  <span class="fu">slice_max</span>(n, <span class="at">n =</span> <span class="dv">4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="chapter-3-forest-stand-structure.html#cb11-5" tabindex="-1"></a>  <span class="fu">pull</span>(Scientific_Name)</span>
<span id="cb11-6"><a href="chapter-3-forest-stand-structure.html#cb11-6" tabindex="-1"></a></span>
<span id="cb11-7"><a href="chapter-3-forest-stand-structure.html#cb11-7" tabindex="-1"></a><span class="co"># Filter the data and plot density curves</span></span>
<span id="cb11-8"><a href="chapter-3-forest-stand-structure.html#cb11-8" tabindex="-1"></a>inventory_clean <span class="sc">%&gt;%</span></span>
<span id="cb11-9"><a href="chapter-3-forest-stand-structure.html#cb11-9" tabindex="-1"></a>  <span class="fu">filter</span>(Scientific_Name <span class="sc">%in%</span> top_4_species) <span class="sc">%&gt;%</span></span>
<span id="cb11-10"><a href="chapter-3-forest-stand-structure.html#cb11-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> DBH_cm, <span class="at">fill =</span> Scientific_Name)) <span class="sc">+</span></span>
<span id="cb11-11"><a href="chapter-3-forest-stand-structure.html#cb11-11" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb11-12"><a href="chapter-3-forest-stand-structure.html#cb11-12" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span> <span class="co"># Adjust based on your max DBH</span></span>
<span id="cb11-13"><a href="chapter-3-forest-stand-structure.html#cb11-13" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Scientific_Name, <span class="at">ncol =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb11-14"><a href="chapter-3-forest-stand-structure.html#cb11-14" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-15"><a href="chapter-3-forest-stand-structure.html#cb11-15" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Diameter Distribution by Species&quot;</span>,</span>
<span id="cb11-16"><a href="chapter-3-forest-stand-structure.html#cb11-16" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;DBH (cm)&quot;</span>,</span>
<span id="cb11-17"><a href="chapter-3-forest-stand-structure.html#cb11-17" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Density&quot;</span></span>
<span id="cb11-18"><a href="chapter-3-forest-stand-structure.html#cb11-18" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-19"><a href="chapter-3-forest-stand-structure.html#cb11-19" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb11-20"><a href="chapter-3-forest-stand-structure.html#cb11-20" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb11-21"><a href="chapter-3-forest-stand-structure.html#cb11-21" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>,</span>
<span id="cb11-22"><a href="chapter-3-forest-stand-structure.html#cb11-22" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;italic&quot;</span>, <span class="at">size =</span> <span class="dv">10</span>)</span>
<span id="cb11-23"><a href="chapter-3-forest-stand-structure.html#cb11-23" tabindex="-1"></a>  )</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:dbh-by-species"></span>
<img src="_main_files/figure-html/dbh-by-species-1.png" alt="Diameter distributions of the top 4 most abundant species, showing their different structural roles." width="672" />
<p class="caption">
Figure 2.2: Diameter distributions of the top 4 most abundant species, showing their different structural roles.
</p>
</div>
<p><strong>Interpretation of Species-specific diameter distributions</strong></p>
<p><strong><em>Plot observations</em></strong>
While the entire forest stand exhibits a classic reverse-J curve, breaking down the diameter distribution by the four most abundant species reveals highly distinct density profiles. Rather than strictly descending exponential curves, these species exhibit unimodal (peak-driven) distributions that highlight their specific structural niches:</p>
<ul>
<li><p>Protium amazonicum displays a sharply defined, narrow peak at the very lowest DBH classes (~10–15 cm) with a steep drop-off, indicating a massive concentration of small stems and very few large individuals.</p></li>
<li><p>Inga ruiziana and Virola duckei show slightly broader distributions peaking around 15–20 cm, with V. duckei displaying a minor secondary bump past 50 cm, hinting at a few surviving canopy adults.</p></li>
<li><p>Pouteria guianensis, the most abundant species in the stand, exhibits the widest and most normally distributed density curve among the four. Its peak is shifted to the right (~20–30 cm), and it maintains a strong presence well into the 40–50 cm DBH range.</p></li>
</ul>
<p><strong><em>Ecological theory and context</em></strong></p>
<p>Analyzing size-class distributions at the species level is a powerful method for inferring life-history strategies, population dynamics, and vertical stratification without needing decades of longitudinal growth data.<span class="citation"><a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a></span> The differing shapes in this plot illustrate how hyperdominant species partition the physical space of the forest:</p>
<ul>
<li><p>Vertical stratification and guilds: The density curves perfectly reflect the distinct ecological guilds (understory, midstory, and canopy) of these taxa. The sharp, left-skewed peak of Protium amazonicum is characteristic of a highly shade-tolerant, midstory specialist. It successfully recruits and persists in the shaded understory but rarely reaches the upper canopy. In contrast, Pouteria guianensis exhibits the signature of a true canopy species; its broader distribution and right-shifted peak indicate that a larger proportion of its individuals successfully recruit into the upper strata and accumulate significant diameter.</p></li>
<li><p>Deconstructing the reverse-J: This plot resolves a common misconception in forest attributes analysis. The stand-level reverse-J curve is not simply the average shape of every species. Instead, as demonstrated by Poorter et al. (2006), the stand-level curve is an aggregate composed of hundreds of different species-specific bell curves, each shifted slightly left or right depending on the species’ maximum potential stature and specific structural role.</p></li>
<li><p>Biomass contributions: From a carbon modeling perspective, this confirms that not all abundant species contribute equally to Aboveground Biomass (AGB). While Protium amazonicum heavily influences stand density and biodiversity metrics, Pouteria guianensis—due to its capacity to sustain larger diameters—plays a vastly disproportionate role in the stand’s total carbon storage.</p></li>
</ul>
</div>
</div>
<div id="d-spatial-distribution-and-mapping" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> 2D Spatial Distribution and Mapping<a href="chapter-3-forest-stand-structure.html#d-spatial-distribution-and-mapping" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Forestry is inherently spatial. Knowing what is in the forest and how big it is only tells half the story; we also need to know exactly where the trees are.</p>
<p>Thanks to the Easting (ESTE) and Northing (NORTE) coordinates collected in the field, we can map our forest stand. In this chapter, we will use the sf (Simple Features) package to convert our standard data table into a spatial object and ggplot2 to map it.</p>
</div>
<div id="creating-spatial-data" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Creating Spatial Data<a href="chapter-3-forest-stand-structure.html#creating-spatial-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Currently, our dataset is just a data frame (a table). To map it, R needs to understand that the Easting and Northing columns represent physical locations on the Earth.</p>
<p>We do this using the st_as_sf() function. We must also define the Coordinate Reference System (CRS). Since these are UTM coordinates (commonly used in South American forest inventories), we will assign an EPSG code. Note: You may need to adjust the EPSG code (e.g., 32718 for UTM Zone 18S) depending on the exact location of your study area.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="chapter-3-forest-stand-structure.html#cb12-1" tabindex="-1"></a><span class="co"># Convert the cleaned data frame into an &#39;sf&#39; spatial object</span></span>
<span id="cb12-2"><a href="chapter-3-forest-stand-structure.html#cb12-2" tabindex="-1"></a>inventory_sf <span class="ot">&lt;-</span> inventory_clean <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="chapter-3-forest-stand-structure.html#cb12-3" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">&quot;Easting&quot;</span>, <span class="st">&quot;Northing&quot;</span>), </span>
<span id="cb12-4"><a href="chapter-3-forest-stand-structure.html#cb12-4" tabindex="-1"></a>           <span class="at">crs =</span> <span class="dv">32718</span>, <span class="co"># Replace with your specific UTM EPSG code if different</span></span>
<span id="cb12-5"><a href="chapter-3-forest-stand-structure.html#cb12-5" tabindex="-1"></a>           <span class="at">remove =</span> <span class="cn">FALSE</span>) <span class="co"># Keep original coordinate columns just in case</span></span>
<span id="cb12-6"><a href="chapter-3-forest-stand-structure.html#cb12-6" tabindex="-1"></a></span>
<span id="cb12-7"><a href="chapter-3-forest-stand-structure.html#cb12-7" tabindex="-1"></a><span class="co"># Verify it is now a spatial object</span></span>
<span id="cb12-8"><a href="chapter-3-forest-stand-structure.html#cb12-8" tabindex="-1"></a><span class="fu">class</span>(inventory_sf)</span></code></pre></div>
<pre><code>## [1] &quot;sf&quot;         &quot;data.frame&quot;</code></pre>
</div>
<div id="advanced-spatial-structure-point-pattern-analysis-by-species" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Advanced Spatial Structure: Point Pattern Analysis by Species<a href="chapter-3-forest-stand-structure.html#advanced-spatial-structure-point-pattern-analysis-by-species" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Analyzing the spatial pattern of all trees combined can mask underlying ecological processes. To truly understand forest dynamics—such as seed dispersal limitations or micro-habitat preferences—we should analyze the spatial distribution of individual species.</p>
<p>We will test whether our most dominant species, Copal (Protium amazonicum), is spatially clustered, randomly distributed, or uniformly spaced. We calculate the Clark-Evans Nearest Neighbor Index (<span class="math inline">\(R\)</span>):<span class="math inline">\(R = 1\)</span>: Random distribution.<span class="math inline">\(R &lt; 1\)</span>: Clustered distribution (e.g., limited seed dispersal, canopy gaps).<span class="math inline">\(R &gt; 1\)</span>: Uniform distribution (e.g., intense competition for resources).We will use the spatstat package to run the statistical test and ggplot2 to visualize the clustering via a 2D density heatmap.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="chapter-3-forest-stand-structure.html#cb14-1" tabindex="-1"></a><span class="co"># Install spatstat if needed: install.packages(&quot;spatstat&quot;)</span></span>
<span id="cb14-2"><a href="chapter-3-forest-stand-structure.html#cb14-2" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span>
<span id="cb14-3"><a href="chapter-3-forest-stand-structure.html#cb14-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb14-4"><a href="chapter-3-forest-stand-structure.html#cb14-4" tabindex="-1"></a></span>
<span id="cb14-5"><a href="chapter-3-forest-stand-structure.html#cb14-5" tabindex="-1"></a><span class="co"># 1. Filter the spatial dataset for a specific species</span></span>
<span id="cb14-6"><a href="chapter-3-forest-stand-structure.html#cb14-6" tabindex="-1"></a>copal_sf <span class="ot">&lt;-</span> inventory_sf <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="chapter-3-forest-stand-structure.html#cb14-7" tabindex="-1"></a>  <span class="fu">filter</span>(Common_Name <span class="sc">==</span> <span class="st">&quot;Copal&quot;</span>)</span>
<span id="cb14-8"><a href="chapter-3-forest-stand-structure.html#cb14-8" tabindex="-1"></a></span>
<span id="cb14-9"><a href="chapter-3-forest-stand-structure.html#cb14-9" tabindex="-1"></a><span class="co"># 2. Extract coordinates for Copal</span></span>
<span id="cb14-10"><a href="chapter-3-forest-stand-structure.html#cb14-10" tabindex="-1"></a>coords_copal <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(copal_sf)</span>
<span id="cb14-11"><a href="chapter-3-forest-stand-structure.html#cb14-11" tabindex="-1"></a></span>
<span id="cb14-12"><a href="chapter-3-forest-stand-structure.html#cb14-12" tabindex="-1"></a><span class="co"># IMPORTANT: We must define the observation window using the boundaries </span></span>
<span id="cb14-13"><a href="chapter-3-forest-stand-structure.html#cb14-13" tabindex="-1"></a><span class="co"># of the ENTIRE plot, not just the Copal trees, to avoid edge-effect errors.</span></span>
<span id="cb14-14"><a href="chapter-3-forest-stand-structure.html#cb14-14" tabindex="-1"></a>all_coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(inventory_sf)</span>
<span id="cb14-15"><a href="chapter-3-forest-stand-structure.html#cb14-15" tabindex="-1"></a>win <span class="ot">&lt;-</span> <span class="fu">owin</span>(<span class="at">xrange =</span> <span class="fu">range</span>(all_coords[,<span class="dv">1</span>]), <span class="at">yrange =</span> <span class="fu">range</span>(all_coords[,<span class="dv">2</span>]))</span>
<span id="cb14-16"><a href="chapter-3-forest-stand-structure.html#cb14-16" tabindex="-1"></a></span>
<span id="cb14-17"><a href="chapter-3-forest-stand-structure.html#cb14-17" tabindex="-1"></a><span class="co"># Create the spatstat point pattern (ppp) object for Copal</span></span>
<span id="cb14-18"><a href="chapter-3-forest-stand-structure.html#cb14-18" tabindex="-1"></a>copal_ppp <span class="ot">&lt;-</span> <span class="fu">ppp</span>(<span class="at">x =</span> coords_copal[,<span class="dv">1</span>], <span class="at">y =</span> coords_copal[,<span class="dv">2</span>], <span class="at">window =</span> win)</span>
<span id="cb14-19"><a href="chapter-3-forest-stand-structure.html#cb14-19" tabindex="-1"></a></span>
<span id="cb14-20"><a href="chapter-3-forest-stand-structure.html#cb14-20" tabindex="-1"></a><span class="co"># 3. Calculate the Clark-Evans test</span></span>
<span id="cb14-21"><a href="chapter-3-forest-stand-structure.html#cb14-21" tabindex="-1"></a>ce_test <span class="ot">&lt;-</span> <span class="fu">clarkevans.test</span>(copal_ppp)</span>
<span id="cb14-22"><a href="chapter-3-forest-stand-structure.html#cb14-22" tabindex="-1"></a></span>
<span id="cb14-23"><a href="chapter-3-forest-stand-structure.html#cb14-23" tabindex="-1"></a><span class="co"># Print the statistical results</span></span>
<span id="cb14-24"><a href="chapter-3-forest-stand-structure.html#cb14-24" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Clark-Evans Index (R) for Copal:&quot;</span>, <span class="fu">round</span>(ce_test<span class="sc">$</span>statistic, <span class="dv">3</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Clark-Evans Index (R) for Copal: 0.916</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="chapter-3-forest-stand-structure.html#cb16-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;p-value:&quot;</span>, <span class="fu">format.pval</span>(ce_test<span class="sc">$</span>p.value), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## p-value: 0.31402</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="chapter-3-forest-stand-structure.html#cb18-1" tabindex="-1"></a><span class="co"># 4. Visualize the clustering using ggplot2</span></span>
<span id="cb18-2"><a href="chapter-3-forest-stand-structure.html#cb18-2" tabindex="-1"></a></span>
<span id="cb18-3"><a href="chapter-3-forest-stand-structure.html#cb18-3" tabindex="-1"></a><span class="co"># Ensure the spatial object is strictly projected in UTM meters</span></span>
<span id="cb18-4"><a href="chapter-3-forest-stand-structure.html#cb18-4" tabindex="-1"></a>copal_sf_utm <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(copal_sf, <span class="at">crs =</span> <span class="dv">32718</span>)</span>
<span id="cb18-5"><a href="chapter-3-forest-stand-structure.html#cb18-5" tabindex="-1"></a>coords_copal_utm <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(copal_sf_utm)</span>
<span id="cb18-6"><a href="chapter-3-forest-stand-structure.html#cb18-6" tabindex="-1"></a>copal_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(coords_copal_utm)</span>
<span id="cb18-7"><a href="chapter-3-forest-stand-structure.html#cb18-7" tabindex="-1"></a></span>
<span id="cb18-8"><a href="chapter-3-forest-stand-structure.html#cb18-8" tabindex="-1"></a></span>
<span id="cb18-9"><a href="chapter-3-forest-stand-structure.html#cb18-9" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb18-10"><a href="chapter-3-forest-stand-structure.html#cb18-10" tabindex="-1"></a>  <span class="co"># Use geom_density_2d_filled for a much cleaner, smoother heatmap</span></span>
<span id="cb18-11"><a href="chapter-3-forest-stand-structure.html#cb18-11" tabindex="-1"></a>  <span class="fu">geom_density_2d_filled</span>(<span class="at">data =</span> copal_df, <span class="fu">aes</span>(<span class="at">x =</span> X, <span class="at">y =</span> Y), <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">bins =</span> <span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb18-12"><a href="chapter-3-forest-stand-structure.html#cb18-12" tabindex="-1"></a>  </span>
<span id="cb18-13"><a href="chapter-3-forest-stand-structure.html#cb18-13" tabindex="-1"></a>  <span class="co"># Add the individual trees on top so we can see the exact locations</span></span>
<span id="cb18-14"><a href="chapter-3-forest-stand-structure.html#cb18-14" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> copal_sf_utm, <span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb18-15"><a href="chapter-3-forest-stand-structure.html#cb18-15" tabindex="-1"></a>  </span>
<span id="cb18-16"><a href="chapter-3-forest-stand-structure.html#cb18-16" tabindex="-1"></a>  <span class="co"># Use a discrete viridis scale since the filled contours create categories</span></span>
<span id="cb18-17"><a href="chapter-3-forest-stand-structure.html#cb18-17" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">&quot;mako&quot;</span>, <span class="at">name =</span> <span class="st">&quot;Density Level&quot;</span>) <span class="sc">+</span></span>
<span id="cb18-18"><a href="chapter-3-forest-stand-structure.html#cb18-18" tabindex="-1"></a>  </span>
<span id="cb18-19"><a href="chapter-3-forest-stand-structure.html#cb18-19" tabindex="-1"></a>  <span class="co"># Force ggplot to use the UTM projection for the axes</span></span>
<span id="cb18-20"><a href="chapter-3-forest-stand-structure.html#cb18-20" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">datum =</span> <span class="fu">st_crs</span>(<span class="dv">32718</span>)) <span class="sc">+</span> </span>
<span id="cb18-21"><a href="chapter-3-forest-stand-structure.html#cb18-21" tabindex="-1"></a>  </span>
<span id="cb18-22"><a href="chapter-3-forest-stand-structure.html#cb18-22" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-23"><a href="chapter-3-forest-stand-structure.html#cb18-23" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Spatial Clustering of Copal Trees&quot;</span>,</span>
<span id="cb18-24"><a href="chapter-3-forest-stand-structure.html#cb18-24" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">&quot;Clark-Evans R = &quot;</span>, <span class="fu">round</span>(ce_test<span class="sc">$</span>statistic, <span class="dv">2</span>)),</span>
<span id="cb18-25"><a href="chapter-3-forest-stand-structure.html#cb18-25" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Easting (m)&quot;</span>,</span>
<span id="cb18-26"><a href="chapter-3-forest-stand-structure.html#cb18-26" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Northing (m)&quot;</span></span>
<span id="cb18-27"><a href="chapter-3-forest-stand-structure.html#cb18-27" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb18-28"><a href="chapter-3-forest-stand-structure.html#cb18-28" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-29"><a href="chapter-3-forest-stand-structure.html#cb18-29" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb18-30"><a href="chapter-3-forest-stand-structure.html#cb18-30" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb18-31"><a href="chapter-3-forest-stand-structure.html#cb18-31" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;right&quot;</span></span>
<span id="cb18-32"><a href="chapter-3-forest-stand-structure.html#cb18-32" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-2-1.png" alt="" width="672" />
The combination of the Clark-Evans test and the 2D density heatmap provides powerful insights into the biology of our forest stand.</p>
<p>First, our Clark-Evans index is <span class="math inline">\(R = 0.92\)</span>. Because <span class="math inline">\(R &lt; 1\)</span>, this indicates that Copal (Protium amazonicum) trees are not randomly scattered; they exhibit a spatially clustered (aggregated) distribution.</p>
<p>This mathematical clustering is visually confirmed by our density heatmap. We can clearly see two distinct “hotspots” of high Copal density (the lightest colored areas) forming a corridor on the eastern side of the plot, while the northwestern corner is almost entirely devoid of this species.</p>
<p>Ecologically, this clustering is usually driven by two primary factors in tropical forests:</p>
<ul>
<li><p>Seed Dispersal Limitation: Copal seeds are often heavy and drop near the parent tree, or they are dispersed by specific animals (like primates or birds) that deposit seeds in concentrated areas beneath resting or feeding sites.</p></li>
<li><p>Micro-habitat Preferences: The “empty” northwestern corner might possess slightly different soil drainage, a different topography, or could be dominated by a highly competitive canopy species that restricts Copal regeneration. The eastern hotspots might represent an area where a historical canopy gap (a tree fall) occurred decades ago, providing the sudden influx of light necessary for a cluster of Copal saplings to successfully establish and grow together.</p></li>
</ul>
<div id="mapping-forest-structure" class="section level3 hasAnchor" number="2.6.1">
<h3><span class="header-section-number">2.6.1</span> Mapping Forest Structure<a href="chapter-3-forest-stand-structure.html#mapping-forest-structure" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now that R knows these are spatial points, plotting them is as easy as adding geom_sf() to our standard ggplot2 workflow.</p>
<p>Let’s start by plotting every tree in the stand. To make the map informative, we will scale the size of each point based on the tree’s diameter (DBH_cm). This allows us to instantly locate the oldest, largest trees in the canopy.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="chapter-3-forest-stand-structure.html#cb19-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> inventory_sf) <span class="sc">+</span></span>
<span id="cb19-2"><a href="chapter-3-forest-stand-structure.html#cb19-2" tabindex="-1"></a>  <span class="co"># Use geom_sf for spatial data, mapping size to DBH</span></span>
<span id="cb19-3"><a href="chapter-3-forest-stand-structure.html#cb19-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">size =</span> DBH_cm), <span class="at">color =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="chapter-3-forest-stand-structure.html#cb19-4" tabindex="-1"></a>  <span class="co"># Adjust the size scale so small trees are visible but large trees don&#39;t overlap too much</span></span>
<span id="cb19-5"><a href="chapter-3-forest-stand-structure.html#cb19-5" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">6</span>), <span class="at">name =</span> <span class="st">&quot;DBH (cm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-6"><a href="chapter-3-forest-stand-structure.html#cb19-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-7"><a href="chapter-3-forest-stand-structure.html#cb19-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Forest stand map: Tree locations and sizes&quot;</span>,</span>
<span id="cb19-8"><a href="chapter-3-forest-stand-structure.html#cb19-8" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">&quot;Larger circles represent trees with greater diameter at breast height&quot;</span>,</span>
<span id="cb19-9"><a href="chapter-3-forest-stand-structure.html#cb19-9" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Easting &quot;</span>,</span>
<span id="cb19-10"><a href="chapter-3-forest-stand-structure.html#cb19-10" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Northing &quot;</span></span>
<span id="cb19-11"><a href="chapter-3-forest-stand-structure.html#cb19-11" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb19-12"><a href="chapter-3-forest-stand-structure.html#cb19-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb19-13"><a href="chapter-3-forest-stand-structure.html#cb19-13" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb19-14"><a href="chapter-3-forest-stand-structure.html#cb19-14" tabindex="-1"></a>    <span class="co"># Angle the x-axis text so the long UTM coordinates don&#39;t overlap</span></span>
<span id="cb19-15"><a href="chapter-3-forest-stand-structure.html#cb19-15" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>) </span>
<span id="cb19-16"><a href="chapter-3-forest-stand-structure.html#cb19-16" tabindex="-1"></a>  )</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:map-structure"></span>
<img src="_main_files/figure-html/map-structure-1.png" alt="Spatial distribution of trees in the inventory plot. Point size correlates to tree diameter." width="672" />
<p class="caption">
Figure 2.3: Spatial distribution of trees in the inventory plot. Point size correlates to tree diameter.
</p>
</div>
<p><strong>Interpretation of spatial distribution and stand mapping</strong></p>
<p><strong><em>Plot observations</em></strong></p>
<p>This bubble map visualizes the precise geo-referenced spatial distribution of all stems within the sampled plot. The axes provide the geographic coordinates (Easting and Northing), placing this stand within the western Amazon basin. Each point represents an individual tree, with the marker size scaled proportionally to its Diameter at Breast Height (DBH). The visual footprint reveals a dense matrix of smaller stems heavily interspersed with occasional large-diameter trees (circles representing DBH &gt; 60 cm), with no large structural voids or canopy gaps currently evident in the mapped area.</p>
<p><strong><em>Ecological theory and context</em></strong></p>
<p>Transitioning from non-spatial histograms to explicit spatial mapping is a critical leap in forest attributes analysis. While diameter distributions tell us what sizes exist, spatial maps tell us how they interact.</p>
<p>This visualization is foundational for understanding local forest dynamics and ecosystem scaling:</p>
<ul>
<li><p>Spatial point pattern analysis: In tropical ecology, the physical arrangement of trees is rarely perfectly random. Researchers use maps like this to run spatial point pattern analyses (e.g., Ripley’s <span class="math inline">\(K\)</span>-function or pair-correlation functions) to determine if trees are clustered, overdispersed, or randomly distributed.<span class="citation"><a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a></span> Clumping often indicates dispersal limitation, while overdispersion can signal intense density-dependent mortality or competition.</p></li>
<li><p>Neighborhood competition: The map illustrates asymmetric competition for light and space. The largest circles (canopy giants) exert a strong competitive “zone of influence” over the surrounding smaller stems. The dense packing of small circles in the interstitial spaces between large trees represents the understory community waiting for a gap-phase disturbance.<span class="citation"><a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a></span></p></li>
<li><p>Upscaling and remote sensing: This geo-referenced map acts as the ultimate bridge between ground-based ecological theory and landscape-level monitoring. Knowing the exact coordinate and DBH of every massive tree allows researchers to accurately calibrate aboveground biomass (AGB) estimates against high-resolution satellite imagery or LiDAR data.<span class="citation"><a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a></span> This ground-truthing is essential for accurately monitoring carbon stocks across the broader Amazonian landscape.</p></li>
</ul>
</div>
<div id="visualizing-species-distribution" class="section level3 hasAnchor" number="2.6.2">
<h3><span class="header-section-number">2.6.2</span> Visualizing Species Distribution<a href="chapter-3-forest-stand-structure.html#visualizing-species-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Some tree species grow in clusters due to seed dispersal mechanisms or soil micro-conditions, while others are randomly scattered. We can visualize this by highlighting specific species on our map.</p>
<p>Looking at our dataset, Protium amazonicum (Copal) and species of the Eschweilera genus (like Machimango) are highly abundant. Let’s create a map that specifically highlights the “Copal” trees against the rest of the stand.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="chapter-3-forest-stand-structure.html#cb20-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> inventory_sf) <span class="sc">+</span></span>
<span id="cb20-2"><a href="chapter-3-forest-stand-structure.html#cb20-2" tabindex="-1"></a>  <span class="co"># Map color to whether the tree is Copal or not</span></span>
<span id="cb20-3"><a href="chapter-3-forest-stand-structure.html#cb20-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">size =</span> DBH_cm, <span class="at">color =</span> Common_Name <span class="sc">==</span> <span class="st">&quot;Copal&quot;</span>), <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a href="chapter-3-forest-stand-structure.html#cb20-4" tabindex="-1"></a>  <span class="co"># Manually set colors: Grey for other trees, Red for Copal</span></span>
<span id="cb20-5"><a href="chapter-3-forest-stand-structure.html#cb20-5" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;grey70&quot;</span>, <span class="st">&quot;firebrick&quot;</span>), </span>
<span id="cb20-6"><a href="chapter-3-forest-stand-structure.html#cb20-6" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Other Species&quot;</span>, <span class="st">&quot;Copal&quot;</span>),</span>
<span id="cb20-7"><a href="chapter-3-forest-stand-structure.html#cb20-7" tabindex="-1"></a>                     <span class="at">name =</span> <span class="st">&quot;Species&quot;</span>) <span class="sc">+</span></span>
<span id="cb20-8"><a href="chapter-3-forest-stand-structure.html#cb20-8" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>), <span class="at">guide =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span> <span class="co"># Hide size legend to keep it clean</span></span>
<span id="cb20-9"><a href="chapter-3-forest-stand-structure.html#cb20-9" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-10"><a href="chapter-3-forest-stand-structure.html#cb20-10" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Spatial Distribution of Copal (Protium amazonicum)&quot;</span>,</span>
<span id="cb20-11"><a href="chapter-3-forest-stand-structure.html#cb20-11" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Easting&quot;</span>,</span>
<span id="cb20-12"><a href="chapter-3-forest-stand-structure.html#cb20-12" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Northing&quot;</span></span>
<span id="cb20-13"><a href="chapter-3-forest-stand-structure.html#cb20-13" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-14"><a href="chapter-3-forest-stand-structure.html#cb20-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-15"><a href="chapter-3-forest-stand-structure.html#cb20-15" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:map-species"></span>
<img src="_main_files/figure-html/map-species-1.png" alt="Highlighting the spatial distribution of Copal (Protium amazonicum) within the stand." width="672" />
<p class="caption">
Figure 2.4: Highlighting the spatial distribution of Copal (Protium amazonicum) within the stand.
</p>
</div>
<p><strong>Interpretation of species-specific spatial distribution</strong></p>
<p><strong><em>Plot observations</em></strong>
This targeted spatial map isolates the distribution of Protium amazonicum (commonly known as Copal, highlighted in red) against the background matrix of all other forest stems (grey). Two distinct patterns immediately emerge. First, corroborating the species-specific diameter distributions analyzed earlier, the red markers are almost exclusively small in diameter; there are no massive canopy-level P. amazonicum individuals in this stand. Second, the spatial arrangement of this species is not perfectly random. There are localized clusters or patches where multiple individuals are packed closely together, as well as broader empty spaces where the species is completely absent.</p>
<p><strong><em>Ecological theory and context</em></strong></p>
<p>Isolating individual species on a geo-referenced grid allows ecologists to move beyond general stand structure and investigate the specific behavioral and life-history traits of hyperdominant taxa:</p>
<ul>
<li><p>Intraspecific vs. Interspecific interactions: By mapping a single species against the rest of the stand, researchers can test for spatial aggregation. The visible clustering of P. amazonicum is a textbook example of dispersal limitation. Because tropical seeds are often gravity-dropped or dispersed by local fauna over very short distances, seedlings tend to germinate in dense “halos” around parent trees.<span class="citation"><a href="#fn10" class="footnote-ref" id="fnref10"><sup>10</sup></a></span></p></li>
<li><p>Microhabitat filtering (niche partitioning): The patchy distribution also hints at micro-topographic or edaphic (soil) preferences. In hyper-diverse Amazonian ecosystems, seemingly uniform forest floors contain subtle gradients in soil moisture, drainage, and nutrient availability. Species like P. amazonicum often aggregate in specific microhabitats where they hold a competitive advantage over other taxa.<span class="citation"><a href="#fn11" class="footnote-ref" id="fnref11"><sup>11</sup></a></span></p></li>
<li><p>Connecting structure to space: This visualization perfectly validates the species-specific DBH histograms discussed previously. We can spatially verify that P. amazonicum acts as a highly successful midstory/understory specialist. It weaves itself through the interstitial spaces between larger canopy giants (the large grey circles), filling the lower strata of the forest architecture without requiring major canopy gaps to survive.</p></li>
</ul>
</div>
</div>
<div id="analyzing-spatial-clustering-with-the-morisita-index" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Analyzing Spatial Clustering with the Morisita Index<a href="chapter-3-forest-stand-structure.html#analyzing-spatial-clustering-with-the-morisita-index" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Visualizing points on a map is incredibly helpful, but our eyes can sometimes deceive us into seeing patterns that aren’t statistically there. To objectively determine if a species is clustered, random, or uniformly distributed, we can calculate the Morisita Index of Dispersion (Id​).</p>
<p>The interpretation of the index is straightforward:</p>
<p><span class="math display">\[Id​&gt;1: Clustered (Aggregated) distribution.\]</span></p>
<p><span class="math display">\[Id​=1: Random distribution.\]</span></p>
<p><span class="math display">\[Id​&lt;1: Uniform (Regular) distribution.\]</span></p>
<p>To calculate this, we need to divide our forest stand into equal-sized quadrats (a grid), count the number of individuals in each quadrat, and apply the Morisita formula. We will use the sf package to create our grid and base R to calculate the math for our most abundant species, Copal (Protium amazonicum).</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="chapter-3-forest-stand-structure.html#cb21-1" tabindex="-1"></a><span class="co"># 1. Filter our spatial data for just the Copal trees</span></span>
<span id="cb21-2"><a href="chapter-3-forest-stand-structure.html#cb21-2" tabindex="-1"></a>copal_sf <span class="ot">&lt;-</span> inventory_sf <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="chapter-3-forest-stand-structure.html#cb21-3" tabindex="-1"></a>  <span class="fu">filter</span>(Common_Name <span class="sc">==</span> <span class="st">&quot;Copal&quot;</span>)</span>
<span id="cb21-4"><a href="chapter-3-forest-stand-structure.html#cb21-4" tabindex="-1"></a></span>
<span id="cb21-5"><a href="chapter-3-forest-stand-structure.html#cb21-5" tabindex="-1"></a><span class="co"># 2. Create a grid (quadrats) over our forest plot</span></span>
<span id="cb21-6"><a href="chapter-3-forest-stand-structure.html#cb21-6" tabindex="-1"></a>plot_grid <span class="ot">&lt;-</span> <span class="fu">st_make_grid</span>(inventory_sf, <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">5</span>)) <span class="co"># 5x5 grid (25 quadrats total)</span></span>
<span id="cb21-7"><a href="chapter-3-forest-stand-structure.html#cb21-7" tabindex="-1"></a></span>
<span id="cb21-8"><a href="chapter-3-forest-stand-structure.html#cb21-8" tabindex="-1"></a><span class="co"># Convert the grid to an sf object so we can map and manipulate it</span></span>
<span id="cb21-9"><a href="chapter-3-forest-stand-structure.html#cb21-9" tabindex="-1"></a>plot_grid_sf <span class="ot">&lt;-</span> <span class="fu">st_sf</span>(<span class="at">quadrat_id =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(plot_grid), <span class="at">geometry =</span> plot_grid)</span>
<span id="cb21-10"><a href="chapter-3-forest-stand-structure.html#cb21-10" tabindex="-1"></a></span>
<span id="cb21-11"><a href="chapter-3-forest-stand-structure.html#cb21-11" tabindex="-1"></a><span class="co"># 3. Count how many Copal trees fall into each quadrat</span></span>
<span id="cb21-12"><a href="chapter-3-forest-stand-structure.html#cb21-12" tabindex="-1"></a>plot_grid_sf<span class="sc">$</span>tree_count <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(plot_grid_sf, copal_sf))</span>
<span id="cb21-13"><a href="chapter-3-forest-stand-structure.html#cb21-13" tabindex="-1"></a></span>
<span id="cb21-14"><a href="chapter-3-forest-stand-structure.html#cb21-14" tabindex="-1"></a><span class="co"># 4. Calculate the Morisita Index mathematically BEFORE plotting</span></span>
<span id="cb21-15"><a href="chapter-3-forest-stand-structure.html#cb21-15" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">nrow</span>(plot_grid_sf)                     <span class="co"># Total number of quadrats (q)</span></span>
<span id="cb21-16"><a href="chapter-3-forest-stand-structure.html#cb21-16" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">sum</span>(plot_grid_sf<span class="sc">$</span>tree_count)           <span class="co"># Total number of Copal trees (N)</span></span>
<span id="cb21-17"><a href="chapter-3-forest-stand-structure.html#cb21-17" tabindex="-1"></a>n <span class="ot">&lt;-</span> plot_grid_sf<span class="sc">$</span>tree_count                <span class="co"># Number of trees in each quadrat (n_i)</span></span>
<span id="cb21-18"><a href="chapter-3-forest-stand-structure.html#cb21-18" tabindex="-1"></a></span>
<span id="cb21-19"><a href="chapter-3-forest-stand-structure.html#cb21-19" tabindex="-1"></a><span class="co"># Morisita Formula: Id = q * [ sum(n * (n - 1)) / (N * (N - 1)) ]</span></span>
<span id="cb21-20"><a href="chapter-3-forest-stand-structure.html#cb21-20" tabindex="-1"></a>morisita_index <span class="ot">&lt;-</span> q <span class="sc">*</span> (<span class="fu">sum</span>(n <span class="sc">*</span> (n <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">/</span> (N <span class="sc">*</span> (N <span class="sc">-</span> <span class="dv">1</span>)))</span>
<span id="cb21-21"><a href="chapter-3-forest-stand-structure.html#cb21-21" tabindex="-1"></a></span>
<span id="cb21-22"><a href="chapter-3-forest-stand-structure.html#cb21-22" tabindex="-1"></a><span class="co"># Determine the distribution string for our plot subtitle</span></span>
<span id="cb21-23"><a href="chapter-3-forest-stand-structure.html#cb21-23" tabindex="-1"></a>dist_type <span class="ot">&lt;-</span> <span class="cf">if</span>(morisita_index <span class="sc">&gt;</span> <span class="dv">1</span>) {</span>
<span id="cb21-24"><a href="chapter-3-forest-stand-structure.html#cb21-24" tabindex="-1"></a>  <span class="st">&quot;CLUSTERED&quot;</span></span>
<span id="cb21-25"><a href="chapter-3-forest-stand-structure.html#cb21-25" tabindex="-1"></a>} <span class="cf">else</span> <span class="cf">if</span> (morisita_index <span class="sc">&lt;</span> <span class="dv">1</span>) {</span>
<span id="cb21-26"><a href="chapter-3-forest-stand-structure.html#cb21-26" tabindex="-1"></a>  <span class="st">&quot;UNIFORM&quot;</span></span>
<span id="cb21-27"><a href="chapter-3-forest-stand-structure.html#cb21-27" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb21-28"><a href="chapter-3-forest-stand-structure.html#cb21-28" tabindex="-1"></a>  <span class="st">&quot;RANDOM&quot;</span></span>
<span id="cb21-29"><a href="chapter-3-forest-stand-structure.html#cb21-29" tabindex="-1"></a>}</span>
<span id="cb21-30"><a href="chapter-3-forest-stand-structure.html#cb21-30" tabindex="-1"></a></span>
<span id="cb21-31"><a href="chapter-3-forest-stand-structure.html#cb21-31" tabindex="-1"></a><span class="co"># 5. Map the quadrats with values overlaid</span></span>
<span id="cb21-32"><a href="chapter-3-forest-stand-structure.html#cb21-32" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb21-33"><a href="chapter-3-forest-stand-structure.html#cb21-33" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> plot_grid_sf, <span class="fu">aes</span>(<span class="at">fill =</span> tree_count), <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-34"><a href="chapter-3-forest-stand-structure.html#cb21-34" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> copal_sf, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb21-35"><a href="chapter-3-forest-stand-structure.html#cb21-35" tabindex="-1"></a>  <span class="co"># This new line adds the tree count numbers centrally over each quadrat grid:</span></span>
<span id="cb21-36"><a href="chapter-3-forest-stand-structure.html#cb21-36" tabindex="-1"></a>  <span class="fu">geom_sf_text</span>(<span class="at">data =</span> plot_grid_sf, <span class="fu">aes</span>(<span class="at">label =</span> tree_count), <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fontface =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb21-37"><a href="chapter-3-forest-stand-structure.html#cb21-37" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">name =</span> <span class="st">&quot;Copal Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-38"><a href="chapter-3-forest-stand-structure.html#cb21-38" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-39"><a href="chapter-3-forest-stand-structure.html#cb21-39" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Spatial distribution &amp; quadrat counts for copal&quot;</span>,</span>
<span id="cb21-40"><a href="chapter-3-forest-stand-structure.html#cb21-40" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">&quot;Morisita Index: &quot;</span>, <span class="fu">round</span>(morisita_index, <span class="dv">3</span>), <span class="st">&quot; (&quot;</span>, dist_type, <span class="st">&quot;)</span><span class="sc">\n</span><span class="st">Red dots denote individual trees.&quot;</span>),</span>
<span id="cb21-41"><a href="chapter-3-forest-stand-structure.html#cb21-41" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Values inside grid cells represent the exact tree count per quadrat.&quot;</span></span>
<span id="cb21-42"><a href="chapter-3-forest-stand-structure.html#cb21-42" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-43"><a href="chapter-3-forest-stand-structure.html#cb21-43" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-3-1.png" alt="" width="672" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="chapter-3-forest-stand-structure.html#cb22-1" tabindex="-1"></a><span class="co"># 6. Print the terminal output</span></span>
<span id="cb22-2"><a href="chapter-3-forest-stand-structure.html#cb22-2" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Total Quadrats (q):&quot;</span>, q, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Total Quadrats (q): 25</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="chapter-3-forest-stand-structure.html#cb24-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Total Copal Trees (N):&quot;</span>, N, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Total Copal Trees (N): 34</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="chapter-3-forest-stand-structure.html#cb26-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Morisita Index (Id):&quot;</span>, <span class="fu">round</span>(morisita_index, <span class="dv">3</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Morisita Index (Id): 1.381</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="chapter-3-forest-stand-structure.html#cb28-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Result: The distribution is&quot;</span>, dist_type, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Result: The distribution is CLUSTERED</code></pre>
<p><strong>Interpretation of spatial aggregation (Morisita Index)</strong></p>
<p><strong><em>Plot observations</em></strong></p>
<p>This quadrat-based map quantifies the spatial arrangement of Protium amazonicum (Copal) across the forest stand. By overlaying a 5x5 grid, the analysis transitions from observing unanchored individual points to measuring localized spatial density. The color gradient and numerical labels immediately highlight a strong spatial bias: the southern edge of the plot contains dense patches (up to 4 and 5 individuals per quadrat), while a large, continuous block in the northwestern sector is completely empty (0 individuals).</p>
<p><strong><em>Ecological theory and context</em></strong></p>
<p>The mathematical confirmation of this visual pattern is provided by the Morisita Index of Dispersion (<span class="math inline">\(I_d\)</span>). This index is a highly robust statistical tool in forest ecology because its results are largely independent of the quadrat size or total population density.</p>
<ul>
<li><p>Clustered distribution: The index uses a threshold of 1.0 to represent a perfectly random (Poisson) distribution. The calculated <span class="math inline">\(I_d\)</span> of 1.381 mathematically dictates that the Copal population is significantly clustered or aggregated.<span class="citation"><a href="#fn12" class="footnote-ref" id="fnref12"><sup>12</sup></a></span></p></li>
<li><p>Ecological drivers: This quantified clustering strongly supports the theories of dispersal limitation and microhabitat filtering discussed in the previous section. The cluster of “empty” quadrats (0 counts) suggests a distinct micro-zone where localized conditions—such as subtle shifts in soil moisture, topography, or intense shading by canopy giants—prevent P. amazonicum recruitment. Conversely, the high-density quadrats represent optimal environmental niches or the direct seed-drop zones surrounding mature parent trees.</p></li>
<li><p>Methodological Value: Quadrat analysis is fundamental in forest attributes analysis because it proves that simple, stand-level averages (e.g., overall stems per hectare) can obscure extreme local variations. A researcher measuring only the top-left corner of this plot would conclude Copal is absent, while one measuring the bottom-right would drastically overestimate its abundance.</p></li>
</ul>
</div>
<div id="spatial-visualization-of-dbh-and-tree-height" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Spatial Visualization of DBH and tree height<a href="chapter-3-forest-stand-structure.html#spatial-visualization-of-dbh-and-tree-height" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>While mapping species presence is crucial, foresters also need to understand the spatial distribution of biomass and canopy structure. Are the tallest trees clustered in a specific valley? Are the widest trees evenly distributed?</p>
<p>We can visualize multiple quantitative parameters simultaneously on a single map. Using our spatial object (inventory_sf),we will map the physical location of each tree, scale the size of the point by its DBH (DBH_cm), and apply a color gradient to represent its total height (Height_m).</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="chapter-3-forest-stand-structure.html#cb30-1" tabindex="-1"></a><span class="co"># Ensure Height is numeric (in case it imported as character)</span></span>
<span id="cb30-2"><a href="chapter-3-forest-stand-structure.html#cb30-2" tabindex="-1"></a>inventory_sf <span class="ot">&lt;-</span> inventory_sf <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="chapter-3-forest-stand-structure.html#cb30-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Height_m =</span> <span class="fu">as.numeric</span>(Height_m)) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="chapter-3-forest-stand-structure.html#cb30-4" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Height_m)) <span class="co"># Remove any rows without height data</span></span>
<span id="cb30-5"><a href="chapter-3-forest-stand-structure.html#cb30-5" tabindex="-1"></a></span>
<span id="cb30-6"><a href="chapter-3-forest-stand-structure.html#cb30-6" tabindex="-1"></a><span class="co"># Create a multi-variable spatial plot</span></span>
<span id="cb30-7"><a href="chapter-3-forest-stand-structure.html#cb30-7" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> inventory_sf) <span class="sc">+</span></span>
<span id="cb30-8"><a href="chapter-3-forest-stand-structure.html#cb30-8" tabindex="-1"></a>  <span class="co"># Map size to DBH, and color to Height</span></span>
<span id="cb30-9"><a href="chapter-3-forest-stand-structure.html#cb30-9" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">size =</span> DBH_cm, <span class="at">color =</span> Height_m), <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb30-10"><a href="chapter-3-forest-stand-structure.html#cb30-10" tabindex="-1"></a>  <span class="co"># Use a viridis color palette which is colorblind-friendly and intuitive for heights</span></span>
<span id="cb30-11"><a href="chapter-3-forest-stand-structure.html#cb30-11" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">&quot;magma&quot;</span>, <span class="at">name =</span> <span class="st">&quot;Total Height (m)&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-12"><a href="chapter-3-forest-stand-structure.html#cb30-12" tabindex="-1"></a>  <span class="co"># Scale the size of the points</span></span>
<span id="cb30-13"><a href="chapter-3-forest-stand-structure.html#cb30-13" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">7</span>), <span class="at">name =</span> <span class="st">&quot;DBH (cm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-14"><a href="chapter-3-forest-stand-structure.html#cb30-14" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb30-15"><a href="chapter-3-forest-stand-structure.html#cb30-15" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Forest structure&quot;</span>,</span>
<span id="cb30-16"><a href="chapter-3-forest-stand-structure.html#cb30-16" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">&quot;Darker/Purple points are lower canopy; Brighter/Yellow points are emergent trees&quot;</span>,</span>
<span id="cb30-17"><a href="chapter-3-forest-stand-structure.html#cb30-17" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Easting&quot;</span>,</span>
<span id="cb30-18"><a href="chapter-3-forest-stand-structure.html#cb30-18" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Northing&quot;</span></span>
<span id="cb30-19"><a href="chapter-3-forest-stand-structure.html#cb30-19" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb30-20"><a href="chapter-3-forest-stand-structure.html#cb30-20" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb30-21"><a href="chapter-3-forest-stand-structure.html#cb30-21" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb30-22"><a href="chapter-3-forest-stand-structure.html#cb30-22" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb30-23"><a href="chapter-3-forest-stand-structure.html#cb30-23" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;right&quot;</span></span>
<span id="cb30-24"><a href="chapter-3-forest-stand-structure.html#cb30-24" tabindex="-1"></a>  )</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:map-dbh-height"></span>
<img src="_main_files/figure-html/map-dbh-height-1.png" alt="Spatial distribution of forest structure. Point size represents DBH (cm) and color represents Total Height (m)." width="672" />
<p class="caption">
Figure 2.5: Spatial distribution of forest structure. Point size represents DBH (cm) and color represents Total Height (m).
</p>
</div>
<p><strong>Interpretation of forest canopy structure and stratification</strong></p>
<p><strong><em>Plot observations</em></strong>
This visualization upgrades the previous spatial point pattern map by layering a fourth dimension of data: Total Tree Height. While the X and Y axes map the spatial coordinates and the bubble size represents Diameter at Breast Height (DBH), the color gradient (from dark purple to bright yellow) quantifies vertical stature.</p>
<p>The plot reveals a “sea” of dark purple circles, indicating that the vast majority of stems are relegated to the lower canopy and understory (roughly 10–15 meters tall). Punctuating this dark matrix are scattered, large, bright yellow and orange markers. These represent the massive emergent trees that exceed 30 meters in height, structurally dominating their immediate spatial neighborhoods. Furthermore, the visual correlation is unmistakable: nearly all bright yellow points are also the largest circles, visually confirming the strict allometric relationship between stem girth and vertical height.</p>
<p><strong><em>Ecological theory and context</em></strong></p>
<p>By integrating height with spatial distribution, this map effectively compresses the complex 3-D architecture of a tropical forest into a readable 2-D plane. This is critical for understanding several advanced ecological dynamics:</p>
<ul>
<li><p>Vertical stratification: Tropical forests are classically defined by their multi-layered vertical architecture.<span class="citation"><a href="#fn13" class="footnote-ref" id="fnref13"><sup>13</sup></a></span> The dark purple points represent the highly shade-tolerant understory and midstory guilds (such as the Protium amazonicum clustered in the previous analysis). The bright yellow points represent the sun-demanding canopy and emergent layers. This stratification partitions light resources and creates distinct microclimates at different vertical levels of the forest.</p></li>
<li><p>Tree allometry and biomechanics: The map visually proves the biomechanical constraints of tree growth. To access the unbroken sunlight of the upper canopy (bright colors), a tree must invest heavily in structural support (large DBH / large circle size) to withstand wind shear and gravitational load.</p></li>
<li><p>3D biomass and remote sensing: Moving from DBH-only models to DBH-plus-height models drastically reduces uncertainty in Aboveground Biomass (AGB) calculations.<span class="citation"><a href="#fn14" class="footnote-ref" id="fnref14"><sup>14</sup></a></span> This exact type of mapped height data is what ecologists use to ground-truth and calibrate airborne LiDAR (Light Detection and Ranging) surveys. The spatial roughness of the canopy—where tall emergent trees create turbulent aerodynamic drag—directly impacts how momentum, heat, and trace gases (like CO₂) mix between the forest and the atmosphere.</p></li>
</ul>
</div>
<div id="biomass-and-carbon-as-structural-attributes" class="section level2 hasAnchor" number="2.9">
<h2><span class="header-section-number">2.9</span> Biomass and carbon as structural attributes<a href="chapter-3-forest-stand-structure.html#biomass-and-carbon-as-structural-attributes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>While DBH and height give us the geometric structure of the forest, Aboveground Biomass (AGB) represents the true physical weight and 3D occupation of the stand.</p>
<p>To calculate AGB without destructively harvesting trees, we use the pantropical allometric model by Chave et al. (2014). This requires our DBH, our estimated Height, and the Wood Specific Gravity (<span class="math inline">\(\rho\)</span>) of each species.</p>
<div id="extracting-wood-density-and-calculating-agb" class="section level3 hasAnchor" number="2.9.1">
<h3><span class="header-section-number">2.9.1</span> Extracting Wood Density and Calculating AGB<a href="chapter-3-forest-stand-structure.html#extracting-wood-density-and-calculating-agb" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can retrieve the regional wood density for our species using the Global Wood Density Database (Zanne et al., 2009) via the <code>BIOMASS</code> package. Once we have all three variables, we calculate AGB (in kg) using the formula:</p>
<p><span class="math display">\[AGB = 0.0673 \times (\rho \times DBH^2 \times H)^{0.976}\]</span></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="chapter-3-forest-stand-structure.html#cb31-1" tabindex="-1"></a><span class="fu">library</span>(BIOMASS)</span>
<span id="cb31-2"><a href="chapter-3-forest-stand-structure.html#cb31-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb31-3"><a href="chapter-3-forest-stand-structure.html#cb31-3" tabindex="-1"></a></span>
<span id="cb31-4"><a href="chapter-3-forest-stand-structure.html#cb31-4" tabindex="-1"></a><span class="co"># 1. Split Scientific Name to get Genus and Species</span></span>
<span id="cb31-5"><a href="chapter-3-forest-stand-structure.html#cb31-5" tabindex="-1"></a>inventory_sf <span class="ot">&lt;-</span> inventory_sf <span class="sc">%&gt;%</span></span>
<span id="cb31-6"><a href="chapter-3-forest-stand-structure.html#cb31-6" tabindex="-1"></a>  <span class="fu">separate</span>(Scientific_Name, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;Genus&quot;</span>, <span class="st">&quot;Species&quot;</span>), </span>
<span id="cb31-7"><a href="chapter-3-forest-stand-structure.html#cb31-7" tabindex="-1"></a>           <span class="at">sep =</span> <span class="st">&quot; &quot;</span>, <span class="at">extra =</span> <span class="st">&quot;drop&quot;</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>)</span>
<span id="cb31-8"><a href="chapter-3-forest-stand-structure.html#cb31-8" tabindex="-1"></a></span>
<span id="cb31-9"><a href="chapter-3-forest-stand-structure.html#cb31-9" tabindex="-1"></a><span class="co"># 2. Retrieve Wood Density for South America (Tropical)</span></span>
<span id="cb31-10"><a href="chapter-3-forest-stand-structure.html#cb31-10" tabindex="-1"></a>wd_data <span class="ot">&lt;-</span> <span class="fu">getWoodDensity</span>(<span class="at">genus =</span> inventory_sf<span class="sc">$</span>Genus,</span>
<span id="cb31-11"><a href="chapter-3-forest-stand-structure.html#cb31-11" tabindex="-1"></a>                          <span class="at">species =</span> inventory_sf<span class="sc">$</span>Species,</span>
<span id="cb31-12"><a href="chapter-3-forest-stand-structure.html#cb31-12" tabindex="-1"></a>                          <span class="at">region =</span> <span class="st">&quot;SouthAmericaTrop&quot;</span>)</span>
<span id="cb31-13"><a href="chapter-3-forest-stand-structure.html#cb31-13" tabindex="-1"></a></span>
<span id="cb31-14"><a href="chapter-3-forest-stand-structure.html#cb31-14" tabindex="-1"></a><span class="co"># 3. Calculate AGB and Carbon (Mg)</span></span>
<span id="cb31-15"><a href="chapter-3-forest-stand-structure.html#cb31-15" tabindex="-1"></a>inventory_sf <span class="ot">&lt;-</span> inventory_sf <span class="sc">%&gt;%</span></span>
<span id="cb31-16"><a href="chapter-3-forest-stand-structure.html#cb31-16" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-17"><a href="chapter-3-forest-stand-structure.html#cb31-17" tabindex="-1"></a>    <span class="at">WoodDensity_g_cm3 =</span> wd_data<span class="sc">$</span>meanWD,</span>
<span id="cb31-18"><a href="chapter-3-forest-stand-structure.html#cb31-18" tabindex="-1"></a>    <span class="co"># Calculate AGB in kg</span></span>
<span id="cb31-19"><a href="chapter-3-forest-stand-structure.html#cb31-19" tabindex="-1"></a>    <span class="at">AGB_kg =</span> <span class="fl">0.0673</span> <span class="sc">*</span> (WoodDensity_g_cm3 <span class="sc">*</span> DBH_cm<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> Height_m)<span class="sc">^</span><span class="fl">0.976</span>,</span>
<span id="cb31-20"><a href="chapter-3-forest-stand-structure.html#cb31-20" tabindex="-1"></a>    <span class="co"># Convert to metric tonnes (Mg)</span></span>
<span id="cb31-21"><a href="chapter-3-forest-stand-structure.html#cb31-21" tabindex="-1"></a>    <span class="at">AGB_Mg =</span> AGB_kg <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb31-22"><a href="chapter-3-forest-stand-structure.html#cb31-22" tabindex="-1"></a>    <span class="co"># Estimate Carbon (47.1% of AGB)</span></span>
<span id="cb31-23"><a href="chapter-3-forest-stand-structure.html#cb31-23" tabindex="-1"></a>    <span class="at">Carbon_Mg =</span> AGB_Mg <span class="sc">*</span> <span class="fl">0.471</span></span>
<span id="cb31-24"><a href="chapter-3-forest-stand-structure.html#cb31-24" tabindex="-1"></a>  )</span>
<span id="cb31-25"><a href="chapter-3-forest-stand-structure.html#cb31-25" tabindex="-1"></a></span>
<span id="cb31-26"><a href="chapter-3-forest-stand-structure.html#cb31-26" tabindex="-1"></a><span class="co"># Summarize the stand totals</span></span>
<span id="cb31-27"><a href="chapter-3-forest-stand-structure.html#cb31-27" tabindex="-1"></a>stand_carbon <span class="ot">&lt;-</span> inventory_sf <span class="sc">%&gt;%</span></span>
<span id="cb31-28"><a href="chapter-3-forest-stand-structure.html#cb31-28" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb31-29"><a href="chapter-3-forest-stand-structure.html#cb31-29" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb31-30"><a href="chapter-3-forest-stand-structure.html#cb31-30" tabindex="-1"></a>    <span class="at">Total_AGB_Mg_ha =</span> <span class="fu">sum</span>(AGB_Mg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb31-31"><a href="chapter-3-forest-stand-structure.html#cb31-31" tabindex="-1"></a>    <span class="at">Total_Carbon_Mg_ha =</span> <span class="fu">sum</span>(Carbon_Mg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb31-32"><a href="chapter-3-forest-stand-structure.html#cb31-32" tabindex="-1"></a>  )</span>
<span id="cb31-33"><a href="chapter-3-forest-stand-structure.html#cb31-33" tabindex="-1"></a></span>
<span id="cb31-34"><a href="chapter-3-forest-stand-structure.html#cb31-34" tabindex="-1"></a><span class="fu">kable</span>(stand_carbon, <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">caption =</span> <span class="st">&quot;Total stand AGB and carbon storage.&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:calc-biomass-structure">Table 2.2: </span>Total stand AGB and carbon storage.</caption>
<thead>
<tr class="header">
<th align="right">Total_AGB_Mg_ha</th>
<th align="right">Total_Carbon_Mg_ha</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">218.58</td>
<td align="right">102.95</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation of total stand biomass and carbon storage</strong></p>
<p><strong><em>Table observations</em></strong></p>
<p>This summary table presents the final, aggregated ecosystem metrics scaled to a per-hectare basis. The stand supports a Total Aboveground Biomass (AGB) of 218.58 Mg ha⁻¹ (Megagrams, or metric tons, per hectare). When converted to elemental carbon, this equates to a Total Carbon storage of 102.95 Mg ha⁻¹.</p>
<p><strong><em>Ecological theory and context</em></strong>
These two numbers represent the ultimate synthesis of all the structural, spatial, and allometric forest attributes analyzed in this chapter. They ground the stand within the broader context of Amazonian biogeochemistry:</p>
<ul>
<li><p>Regional biomass baselines: An AGB of ~219 Mg ha⁻¹ falls squarely within the expected range for intact terra firme forests in the western Amazon. Due to more fertile soils and different disturbance regimes, western Amazonian forests typically exhibit higher turnover rates and slightly lower standing biomass than the slower-growing, denser forests of the central and eastern basin.<span class="citation"><a href="#fn15" class="footnote-ref" id="fnref15"><sup>15</sup></a></span></p></li>
<li><p>The Biomass-to-Carbon conversion: The table highlights that AGB and Carbon are not a 1:1 ratio. The calculation relies on the well-established ecological constant that tropical angiosperm wood is composed of approximately 47% to 50% carbon by dry mass.<span class="citation"><a href="#fn16" class="footnote-ref" id="fnref16"><sup>16</sup></a></span> The ratio here (102.95 / 218.58 = ~0.471) reflects the rigorous application of this ~47.1% conversion factor, avoiding the overestimations that occur when using a generic 50% multiplier.</p></li>
<li><p>Structural synthesis: This final carbon tally mathematically validates the “biomass paradox” observed in the previous diameter and canopy height maps. While the understory is packed with hundreds of small stems, the bulk of this 102.95 Mg ha⁻¹ carbon reservoir is physically locked inside the massive trunks and complex branch networks of the few towering canopy emergents (the &gt;60 cm DBH trees). Accurately estimating this number requires integrating tree height, diameter, and species-specific wood density into robust pantropical allometric models.<span class="citation"><a href="#fn17" class="footnote-ref" id="fnref17"><sup>17</sup></a></span></p></li>
</ul>
</div>
</div>
<div id="spatial-distribution-of-carbon" class="section level2 hasAnchor" number="2.10">
<h2><span class="header-section-number">2.10</span> Spatial distribution of carbon<a href="chapter-3-forest-stand-structure.html#spatial-distribution-of-carbon" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Forest biomass is rarely distributed evenly. In old-growth Amazonian stands, massive emergent trees dictate the canopy structure and can store up to 50% of the total carbon. By mapping our carbon estimates, we can identify these structural “hotspots.”</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="chapter-3-forest-stand-structure.html#cb32-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> inventory_sf) <span class="sc">+</span></span>
<span id="cb32-2"><a href="chapter-3-forest-stand-structure.html#cb32-2" tabindex="-1"></a>  <span class="co"># Map size and color to the Carbon variable</span></span>
<span id="cb32-3"><a href="chapter-3-forest-stand-structure.html#cb32-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">size =</span> Carbon_Mg, <span class="at">color =</span> Carbon_Mg), <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="chapter-3-forest-stand-structure.html#cb32-4" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">&quot;inferno&quot;</span>, <span class="at">name =</span> <span class="st">&quot;Carbon (Mg)&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-5"><a href="chapter-3-forest-stand-structure.html#cb32-5" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="fl">1.5</span>, <span class="dv">8</span>), <span class="at">guide =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="chapter-3-forest-stand-structure.html#cb32-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb32-7"><a href="chapter-3-forest-stand-structure.html#cb32-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Structural carbon hotspots&quot;</span>,</span>
<span id="cb32-8"><a href="chapter-3-forest-stand-structure.html#cb32-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Easting (UTM m)&quot;</span>,</span>
<span id="cb32-9"><a href="chapter-3-forest-stand-structure.html#cb32-9" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Northing (UTM m)&quot;</span></span>
<span id="cb32-10"><a href="chapter-3-forest-stand-structure.html#cb32-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb32-11"><a href="chapter-3-forest-stand-structure.html#cb32-11" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-12"><a href="chapter-3-forest-stand-structure.html#cb32-12" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb32-13"><a href="chapter-3-forest-stand-structure.html#cb32-13" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb32-14"><a href="chapter-3-forest-stand-structure.html#cb32-14" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;right&quot;</span></span>
<span id="cb32-15"><a href="chapter-3-forest-stand-structure.html#cb32-15" tabindex="-1"></a>  )</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:map-carbon-structure"></span>
<img src="_main_files/figure-html/map-carbon-structure-1.png" alt="Spatial distribution of structural carbon. Bright yellow circles indicate massive trees dominating the canopy structure and carbon pool." width="672" />
<p class="caption">
Figure 2.6: Spatial distribution of structural carbon. Bright yellow circles indicate massive trees dominating the canopy structure and carbon pool.
</p>
</div>
<p><strong>Interpretation of structural carbon hotspots</strong></p>
<p><strong><em>Plot observations</em></strong>
This spatial map translates the forest’s physical structure directly into elemental carbon storage. By scaling both the size and the color gradient of the points to represent Carbon (Mg) per individual tree, the visualization highlights extreme spatial heterogeneity. The plot is dominated by a dense matrix of small, dark purple dots, indicating that the vast majority of individual stems store less than 0.5 Mg of carbon. In stark contrast, a sparse scattering of bright orange and yellow markers reveals the locations of the stand’s “carbon hotspots”—massive individual trees that each sequester upwards of 2.0 to 2.5 Mg of carbon.</p>
<p><strong><em>Ecological theory and context</em></strong>
Mapping carbon spatially rather than just structurally provides critical insights into forest vulnerability, disturbance regimes, and overarching biogeochemical cycles:</p>
<ul>
<li><p>The carbon oligarchy: This visual perfectly encapsulates the hyperdominance of carbon storage in Amazonian ecosystems.<span class="citation"><a href="#fn18" class="footnote-ref" id="fnref18"><sup>18</sup></a></span> While the understory contains hundreds of stems, the ecosystem’s total carbon capacity is disproportionately anchored by a highly select oligarchy of canopy giants.</p></li>
<li><p>Disturbance dynamics: Because the stand’s carbon is so heavily concentrated in these few bright yellow hotspots, the forest’s overall carbon balance is highly sensitive to the mortality of large trees. When these massive individuals succumb to storm-driven windthrow events or natural senescence, they instantly transfer immense amounts of sequestered carbon into the dead wood (necromass) pool.<span class="citation"><a href="#fn19" class="footnote-ref" id="fnref19"><sup>19</sup></a></span></p></li>
<li><p>Spatial gap creation: The fall of one of these 2.5 Mg giants does not just shift carbon pools; it physically crushes neighboring smaller stems and tears open massive canopy gaps. This localized destruction restarts the successional clock in that specific spatial coordinate, driving the gap-phase regeneration cycles necessary to maintain the reverse-J diameter distribution we observed earlier.</p></li>
</ul>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>H Arthur Meyer, <span>“Structure, Growth, and Drain in Balanced Uneven-Aged Forests,”</span> <em>Journal of Forestry</em> 50, no. 2 (1952): 85–92.<a href="chapter-3-forest-stand-structure.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>David A Clark and Deborah B Clark, <span>“Life History Diversity of Canopy and Emergent Trees in a Neotropical Rain Forest,”</span> <em>Ecological Monographs</em> 62, no. 3 (1992): 315–44, <a href="https://doi.org/10.2307/2937114">https://doi.org/10.2307/2937114</a>.<a href="chapter-3-forest-stand-structure.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p><span class="nocase">JWF Slik et al.</span>, <span>“Large Trees Drive Forest Aboveground Biomass Variation in Moist Lowland Forests Across the Tropics,”</span> <em>Global Ecology and Biogeography</em> 22, no. 12 (2013): 1261–71, <a href="https://doi.org/10.1111/geb.12092">https://doi.org/10.1111/geb.12092</a>.<a href="chapter-3-forest-stand-structure.html#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>Thomas Eugene Avery and Harold E Burkhart, <em>Forest Measurements</em> (Waveland Press, 2015).<a href="chapter-3-forest-stand-structure.html#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p><span class="nocase">Helene C Muller-Landau et al.</span>, <span>“Comparing Tropical Forest Tree Size Distributions with the Predictions of Metabolic Ecology and Equilibrium Models,”</span> <em>Ecology Letters</em> 9, no. 5 (2006): 589–602, <a href="https://doi.org/10.1111/j.1461-0248.2006.00915.x">https://doi.org/10.1111/j.1461-0248.2006.00915.x</a>.<a href="chapter-3-forest-stand-structure.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>Richard Condit et al., <span>“Inferring Population Dynamics from Size Distributions in Tropical Forest Trees,”</span> <em>The American Naturalist</em> 151, no. 3 (1998): 239–50, <a href="https://doi.org/10.1086/286115">https://doi.org/10.1086/286115</a>.<a href="chapter-3-forest-stand-structure.html#fnref6" class="footnote-back">↩︎</a></p></li>
<li id="fn7"><p>Thorsten Wiegand and Kirk A Moloney, <em>Handbook of Spatial Point-Pattern Analysis in Ecology</em> (CRC press, 2014).<a href="chapter-3-forest-stand-structure.html#fnref7" class="footnote-back">↩︎</a></p></li>
<li id="fn8"><p>James A Lutz et al., <span>“The Importance of Large-Diameter Trees to Forest Structural Heterogeneity,”</span> <em>PLoS ONE</em> 7, no. 5 (2012): e36131, <a href="https://doi.org/10.1371/journal.pone.0036131">https://doi.org/10.1371/journal.pone.0036131</a>.<a href="chapter-3-forest-stand-structure.html#fnref8" class="footnote-back">↩︎</a></p></li>
<li id="fn9"><p>Jérôme Chave et al., <span>“Spatial and Temporal Variation of Biomass in a Tropical Forest: Results from a Large Census Plot in Panama,”</span> <em>Journal of Ecology</em> 91, no. 2 (2003): 240–52, <a href="https://doi.org/10.1046/j.1365-2745.2003.00757.x">https://doi.org/10.1046/j.1365-2745.2003.00757.x</a>.<a href="chapter-3-forest-stand-structure.html#fnref9" class="footnote-back">↩︎</a></p></li>
<li id="fn10"><p><span class="nocase">Richard Condit et al.</span>, <span>“Spatial Patterns in the Distribution of Tropical Tree Species,”</span> <em>Science</em> 288, no. 5470 (2000): 1414–18, <a href="https://doi.org/10.1126/science.288.5470.1414">https://doi.org/10.1126/science.288.5470.1414</a>.<a href="chapter-3-forest-stand-structure.html#fnref10" class="footnote-back">↩︎</a></p></li>
<li id="fn11"><p>Kyle E Harms et al., <span>“Habitat Associations of Trees and Shrubs in a 50-Ha Neotropical Forest Plot,”</span> <em>Journal of Ecology</em> 89, no. 6 (2001): 947–59, <a href="https://doi.org/10.1111/j.1365-2745.2001.00615.x">https://doi.org/10.1111/j.1365-2745.2001.00615.x</a>.<a href="chapter-3-forest-stand-structure.html#fnref11" class="footnote-back">↩︎</a></p></li>
<li id="fn12"><p>Masaaki Morisita, <span>“Measuring of the Dispersion of Individuals and Analysis of the Distributional Patterns,”</span> <em>Memoirs of the Faculty of Science, Kyushu University Series E (Biology)</em> 2, no. 4 (1959): 215–35.<a href="chapter-3-forest-stand-structure.html#fnref12" class="footnote-back">↩︎</a></p></li>
<li id="fn13"><p>Paul Westmacott Richards, <em>The Tropical Rain Forest: An Ecological Study</em> (Cambridge University Press, 1996).<a href="chapter-3-forest-stand-structure.html#fnref13" class="footnote-back">↩︎</a></p></li>
<li id="fn14"><p><span class="nocase">Ted R Feldpausch et al.</span>, <span>“Tree Height Integrated into Pantropical Forest Biomass Estimates,”</span> <em>Biogeosciences</em> 9, no. 8 (2012): 3381–403, <a href="https://doi.org/10.5194/bg-9-3381-2012">https://doi.org/10.5194/bg-9-3381-2012</a>.<a href="chapter-3-forest-stand-structure.html#fnref14" class="footnote-back">↩︎</a></p></li>
<li id="fn15"><p><span class="nocase">Edward TA Mitchard et al.</span>, <span>“Markedly Divergent Estimates of Amazon Forest Carbon Density from Ground Plots and Satellites,”</span> <em>Global Ecology and Biogeography</em> 23, no. 8 (2014): 935–46, <a href="https://doi.org/10.1111/geb.12168">https://doi.org/10.1111/geb.12168</a>.<a href="chapter-3-forest-stand-structure.html#fnref15" class="footnote-back">↩︎</a></p></li>
<li id="fn16"><p>Adam R Martin and Sean C Thomas, <span>“A Reassessment of Carbon Content in Tropical Trees,”</span> <em>PLoS ONE</em> 6, no. 8 (2011): e23533, <a href="https://doi.org/10.1371/journal.pone.0023533">https://doi.org/10.1371/journal.pone.0023533</a>.<a href="chapter-3-forest-stand-structure.html#fnref16" class="footnote-back">↩︎</a></p></li>
<li id="fn17"><p><span class="nocase">Jérôme Chave et al.</span>, <span>“Improved Allometric Models to Estimate the Aboveground Biomass of Tropical Trees,”</span> <em>Global Change Biology</em> 20, no. 10 (2014): 3177–90, <a href="https://doi.org/10.1111/gcb.12629">https://doi.org/10.1111/gcb.12629</a>.<a href="chapter-3-forest-stand-structure.html#fnref17" class="footnote-back">↩︎</a></p></li>
<li id="fn18"><p><span class="nocase">Sophie Fauset et al.</span>, <span>“Hyperdominance in Amazonian Forest Carbon Cycling,”</span> <em>Nature Communications</em> 6, no. 1 (2015): 6857, <a href="https://doi.org/10.1038/ncomms7857">https://doi.org/10.1038/ncomms7857</a>.<a href="chapter-3-forest-stand-structure.html#fnref18" class="footnote-back">↩︎</a></p></li>
<li id="fn19"><p>David Urquiza-Muñoz J et al., <span>“Tracking Amazon Forest Succession After Large-Scale Windthrow Events,”</span> <em>Environmental Research: Ecology</em> 5, no. 2 (2026): 025004, <a href="https://doi.org/10.1088/2752-664X/ae6784">https://doi.org/10.1088/2752-664X/ae6784</a>.<a href="chapter-3-forest-stand-structure.html#fnref19" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

            </section>

          </div>
        </div>
      </div>
<a href="chapter-1-introduction-to-forest-data-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter-2-forest-composition-structure.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "sepia",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
